#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 140
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 56
#define ALIAS_COUNT 1
#define TOKEN_COUNT 26
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 4

enum {
  anon_sym_DOT = 1,
  anon_sym__ = 2,
  anon_sym_COLON = 3,
  anon_sym_EQ = 4,
  anon_sym_PERCENTdefine = 5,
  anon_sym_PERCENTsolve = 6,
  anon_sym_DASH_GT = 7,
  anon_sym_LT_DASH = 8,
  anon_sym_LBRACE = 9,
  anon_sym_RBRACE = 10,
  anon_sym_LBRACK = 11,
  anon_sym_RBRACK = 12,
  anon_sym_LPAREN = 13,
  anon_sym_RPAREN = 14,
  anon_sym_type = 15,
  anon_sym_PLUS = 16,
  anon_sym_STAR = 17,
  anon_sym_DASH = 18,
  anon_sym_PERCENTmode = 19,
  anon_sym_PERCENTtotal = 20,
  anon_sym_PERCENTworlds = 21,
  anon_sym_PIPE = 22,
  anon_sym_PERCENTfreeze = 23,
  sym_comment = 24,
  sym_id = 25,
  sym_source_file = 26,
  sym__declaration = 27,
  sym_con_decl = 28,
  sym_defn = 29,
  sym__solve_defn = 30,
  sym_solve_decl = 31,
  sym_tm_fun = 32,
  sym_tm_pi = 33,
  sym_tm_lam = 34,
  sym_tm_app = 35,
  sym_tm_ascrip = 36,
  sym_tm_bracket = 37,
  sym__term = 38,
  sym_mode = 39,
  sym_mid = 40,
  sym_mode_decl = 41,
  sym_callpat = 42,
  sym_order = 43,
  sym_total_decl = 44,
  sym_worlds_decl = 45,
  sym_freeze_decl = 46,
  aux_sym_source_file_repeat1 = 47,
  aux_sym_solve_decl_repeat1 = 48,
  aux_sym_mode_decl_repeat1 = 49,
  aux_sym_mode_decl_repeat2 = 50,
  aux_sym_mode_decl_repeat3 = 51,
  aux_sym_callpat_repeat1 = 52,
  aux_sym_order_repeat1 = 53,
  aux_sym_total_decl_repeat1 = 54,
  aux_sym_worlds_decl_repeat1 = 55,
  alias_sym_tm_hole = 56,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_DOT] = ".",
  [anon_sym__] = "anon",
  [anon_sym_COLON] = ":",
  [anon_sym_EQ] = "=",
  [anon_sym_PERCENTdefine] = "%define",
  [anon_sym_PERCENTsolve] = "%solve",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_LT_DASH] = "<-",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_type] = "tm_type",
  [anon_sym_PLUS] = "+",
  [anon_sym_STAR] = "*",
  [anon_sym_DASH] = "-",
  [anon_sym_PERCENTmode] = "%mode",
  [anon_sym_PERCENTtotal] = "%total",
  [anon_sym_PERCENTworlds] = "%worlds",
  [anon_sym_PIPE] = "|",
  [anon_sym_PERCENTfreeze] = "%freeze",
  [sym_comment] = "comment",
  [sym_id] = "id",
  [sym_source_file] = "source_file",
  [sym__declaration] = "_declaration",
  [sym_con_decl] = "con_decl",
  [sym_defn] = "defn",
  [sym__solve_defn] = "_solve_defn",
  [sym_solve_decl] = "solve_decl",
  [sym_tm_fun] = "tm_fun",
  [sym_tm_pi] = "tm_pi",
  [sym_tm_lam] = "tm_lam",
  [sym_tm_app] = "tm_app",
  [sym_tm_ascrip] = "tm_ascrip",
  [sym_tm_bracket] = "tm_bracket",
  [sym__term] = "_term",
  [sym_mode] = "mode",
  [sym_mid] = "mid",
  [sym_mode_decl] = "mode_decl",
  [sym_callpat] = "callpat",
  [sym_order] = "order",
  [sym_total_decl] = "total_decl",
  [sym_worlds_decl] = "worlds_decl",
  [sym_freeze_decl] = "freeze_decl",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_solve_decl_repeat1] = "solve_decl_repeat1",
  [aux_sym_mode_decl_repeat1] = "mode_decl_repeat1",
  [aux_sym_mode_decl_repeat2] = "mode_decl_repeat2",
  [aux_sym_mode_decl_repeat3] = "mode_decl_repeat3",
  [aux_sym_callpat_repeat1] = "callpat_repeat1",
  [aux_sym_order_repeat1] = "order_repeat1",
  [aux_sym_total_decl_repeat1] = "total_decl_repeat1",
  [aux_sym_worlds_decl_repeat1] = "worlds_decl_repeat1",
  [alias_sym_tm_hole] = "tm_hole",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym__] = anon_sym__,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_PERCENTdefine] = anon_sym_PERCENTdefine,
  [anon_sym_PERCENTsolve] = anon_sym_PERCENTsolve,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_LT_DASH] = anon_sym_LT_DASH,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_PERCENTmode] = anon_sym_PERCENTmode,
  [anon_sym_PERCENTtotal] = anon_sym_PERCENTtotal,
  [anon_sym_PERCENTworlds] = anon_sym_PERCENTworlds,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_PERCENTfreeze] = anon_sym_PERCENTfreeze,
  [sym_comment] = sym_comment,
  [sym_id] = sym_id,
  [sym_source_file] = sym_source_file,
  [sym__declaration] = sym__declaration,
  [sym_con_decl] = sym_con_decl,
  [sym_defn] = sym_defn,
  [sym__solve_defn] = sym__solve_defn,
  [sym_solve_decl] = sym_solve_decl,
  [sym_tm_fun] = sym_tm_fun,
  [sym_tm_pi] = sym_tm_pi,
  [sym_tm_lam] = sym_tm_lam,
  [sym_tm_app] = sym_tm_app,
  [sym_tm_ascrip] = sym_tm_ascrip,
  [sym_tm_bracket] = sym_tm_bracket,
  [sym__term] = sym__term,
  [sym_mode] = sym_mode,
  [sym_mid] = sym_mid,
  [sym_mode_decl] = sym_mode_decl,
  [sym_callpat] = sym_callpat,
  [sym_order] = sym_order,
  [sym_total_decl] = sym_total_decl,
  [sym_worlds_decl] = sym_worlds_decl,
  [sym_freeze_decl] = sym_freeze_decl,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_solve_decl_repeat1] = aux_sym_solve_decl_repeat1,
  [aux_sym_mode_decl_repeat1] = aux_sym_mode_decl_repeat1,
  [aux_sym_mode_decl_repeat2] = aux_sym_mode_decl_repeat2,
  [aux_sym_mode_decl_repeat3] = aux_sym_mode_decl_repeat3,
  [aux_sym_callpat_repeat1] = aux_sym_callpat_repeat1,
  [aux_sym_order_repeat1] = aux_sym_order_repeat1,
  [aux_sym_total_decl_repeat1] = aux_sym_total_decl_repeat1,
  [aux_sym_worlds_decl_repeat1] = aux_sym_worlds_decl_repeat1,
  [alias_sym_tm_hole] = alias_sym_tm_hole,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENTdefine] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENTsolve] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENTmode] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENTtotal] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENTworlds] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENTfreeze] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_id] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__declaration] = {
    .visible = false,
    .named = true,
  },
  [sym_con_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_defn] = {
    .visible = true,
    .named = true,
  },
  [sym__solve_defn] = {
    .visible = false,
    .named = true,
  },
  [sym_solve_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_tm_fun] = {
    .visible = true,
    .named = true,
  },
  [sym_tm_pi] = {
    .visible = true,
    .named = true,
  },
  [sym_tm_lam] = {
    .visible = true,
    .named = true,
  },
  [sym_tm_app] = {
    .visible = true,
    .named = true,
  },
  [sym_tm_ascrip] = {
    .visible = true,
    .named = true,
  },
  [sym_tm_bracket] = {
    .visible = true,
    .named = true,
  },
  [sym__term] = {
    .visible = false,
    .named = true,
  },
  [sym_mode] = {
    .visible = true,
    .named = true,
  },
  [sym_mid] = {
    .visible = true,
    .named = true,
  },
  [sym_mode_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_callpat] = {
    .visible = true,
    .named = true,
  },
  [sym_order] = {
    .visible = true,
    .named = true,
  },
  [sym_total_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_worlds_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_freeze_decl] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_solve_decl_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_mode_decl_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_mode_decl_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_mode_decl_repeat3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_callpat_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_order_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_total_decl_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_worlds_decl_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_tm_hole] = {
    .visible = true,
    .named = true,
  },
};

enum {
  field_from = 1,
  field_to = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_from] = "from",
  [field_to] = "to",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [2] = {.index = 0, .length = 2},
  [3] = {.index = 2, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_from, 0},
    {field_to, 2},
  [2] =
    {field_from, 2},
    {field_to, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = alias_sym_tm_hole,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 3,
  [16] = 7,
  [17] = 6,
  [18] = 5,
  [19] = 4,
  [20] = 8,
  [21] = 2,
  [22] = 9,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 24,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 23,
  [31] = 31,
  [32] = 28,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 42,
  [46] = 41,
  [47] = 47,
  [48] = 48,
  [49] = 47,
  [50] = 43,
  [51] = 51,
  [52] = 36,
  [53] = 53,
  [54] = 38,
  [55] = 55,
  [56] = 56,
  [57] = 48,
  [58] = 58,
  [59] = 44,
  [60] = 60,
  [61] = 37,
  [62] = 62,
  [63] = 53,
  [64] = 34,
  [65] = 35,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 109,
  [123] = 113,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 127,
  [136] = 130,
  [137] = 137,
  [138] = 138,
  [139] = 139,
};

static inline bool sym_id_character_set_1(int32_t c) {
  return (c < ':'
    ? (c < '('
      ? (c < '"'
        ? c == 0
        : c <= '"')
      : (c <= '(' || c == '.'))
    : (c <= ':' || (c < '{'
      ? (c < ']'
        ? c == '['
        : c <= ']')
      : (c <= '{' || c == '}'))));
}

static inline bool sym_id_character_set_2(int32_t c) {
  return (c < '('
    ? (c < ' '
      ? (c < '\t'
        ? c == 0
        : (c <= '\n' || c == '\r'))
      : (c <= ' ' || (c < '%'
        ? c == '"'
        : c <= '%')))
    : (c <= ')' || (c < ']'
      ? (c < ':'
        ? c == '.'
        : (c <= ':' || c == '['))
      : (c <= ']' || (c < '}'
        ? c == '{'
        : c <= '}')))));
}

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(39);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (lookahead == '%') ADVANCE(1);
      if (lookahead == '(') ADVANCE(55);
      if (lookahead == ')') ADVANCE(56);
      if (lookahead == '*') ADVANCE(60);
      if (lookahead == '+') ADVANCE(59);
      if (lookahead == '-') ADVANCE(61);
      if (lookahead == '.') ADVANCE(40);
      if (lookahead == ':') ADVANCE(43);
      if (lookahead == '<') ADVANCE(4);
      if (lookahead == '=') ADVANCE(44);
      if (lookahead == '[') ADVANCE(53);
      if (lookahead == ']') ADVANCE(54);
      if (lookahead == '_') ADVANCE(41);
      if (lookahead == 't') ADVANCE(32);
      if (lookahead == '{') ADVANCE(51);
      if (lookahead == '|') ADVANCE(65);
      if (lookahead == '}') ADVANCE(52);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(67);
      if (lookahead == 'd') ADVANCE(8);
      if (lookahead == 'f') ADVANCE(27);
      if (lookahead == 'm') ADVANCE(22);
      if (lookahead == 's') ADVANCE(23);
      if (lookahead == 't') ADVANCE(24);
      if (lookahead == 'w') ADVANCE(25);
      if (lookahead == '\t' ||
          lookahead == ' ' ||
          lookahead == '%') ADVANCE(68);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(67);
      if (lookahead == 'd') ADVANCE(8);
      if (lookahead == 's') ADVANCE(23);
      if (lookahead == '\t' ||
          lookahead == ' ' ||
          lookahead == '%') ADVANCE(68);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(67);
      if (lookahead == '\t' ||
          lookahead == ' ' ||
          lookahead == '%') ADVANCE(68);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(49);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(19);
      END_STATE();
    case 6:
      if (lookahead == 'd') ADVANCE(29);
      END_STATE();
    case 7:
      if (lookahead == 'd') ADVANCE(11);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(57);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(33);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(62);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(47);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(46);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(66);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(10);
      END_STATE();
    case 16:
      if (lookahead == 'f') ADVANCE(17);
      END_STATE();
    case 17:
      if (lookahead == 'i') ADVANCE(21);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(31);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(63);
      END_STATE();
    case 20:
      if (lookahead == 'l') ADVANCE(6);
      END_STATE();
    case 21:
      if (lookahead == 'n') ADVANCE(13);
      END_STATE();
    case 22:
      if (lookahead == 'o') ADVANCE(7);
      END_STATE();
    case 23:
      if (lookahead == 'o') ADVANCE(18);
      END_STATE();
    case 24:
      if (lookahead == 'o') ADVANCE(30);
      END_STATE();
    case 25:
      if (lookahead == 'o') ADVANCE(28);
      END_STATE();
    case 26:
      if (lookahead == 'p') ADVANCE(9);
      END_STATE();
    case 27:
      if (lookahead == 'r') ADVANCE(15);
      END_STATE();
    case 28:
      if (lookahead == 'r') ADVANCE(20);
      END_STATE();
    case 29:
      if (lookahead == 's') ADVANCE(64);
      END_STATE();
    case 30:
      if (lookahead == 't') ADVANCE(5);
      END_STATE();
    case 31:
      if (lookahead == 'v') ADVANCE(12);
      END_STATE();
    case 32:
      if (lookahead == 'y') ADVANCE(26);
      END_STATE();
    case 33:
      if (lookahead == 'z') ADVANCE(14);
      END_STATE();
    case 34:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(34)
      if (lookahead == '%') ADVANCE(2);
      if (lookahead == '(') ADVANCE(55);
      if (lookahead == ')') ADVANCE(56);
      if (lookahead == '-') ADVANCE(70);
      if (lookahead == '.') ADVANCE(40);
      if (lookahead == ':') ADVANCE(43);
      if (lookahead == '<') ADVANCE(69);
      if (lookahead == '[') ADVANCE(53);
      if (lookahead == ']') ADVANCE(54);
      if (lookahead == '_') ADVANCE(42);
      if (lookahead == 't') ADVANCE(73);
      if (lookahead == '{') ADVANCE(51);
      if (lookahead == '}') ADVANCE(52);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(74);
      END_STATE();
    case 35:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(35)
      if (lookahead == '%') ADVANCE(3);
      if (lookahead == '(') ADVANCE(55);
      if (lookahead == '-') ADVANCE(70);
      if (lookahead == '.') ADVANCE(40);
      if (lookahead == ':') ADVANCE(43);
      if (lookahead == '<') ADVANCE(69);
      if (lookahead == '=') ADVANCE(45);
      if (lookahead == '[') ADVANCE(53);
      if (lookahead == '_') ADVANCE(42);
      if (lookahead == 't') ADVANCE(73);
      if (lookahead == '{') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != ')' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(74);
      END_STATE();
    case 36:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(36)
      if (lookahead == '%') ADVANCE(3);
      if (lookahead == '(') ADVANCE(55);
      if (lookahead == '[') ADVANCE(53);
      if (lookahead == '_') ADVANCE(42);
      if (lookahead == 't') ADVANCE(73);
      if (lookahead == '{') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != ')' &&
          lookahead != '.' &&
          lookahead != ':' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(74);
      END_STATE();
    case 37:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(37)
      if (lookahead == '%') ADVANCE(3);
      if (lookahead == '(') ADVANCE(55);
      if (lookahead == ')') ADVANCE(56);
      if (lookahead == '.') ADVANCE(40);
      if (lookahead == '[') ADVANCE(53);
      if (lookahead == ']') ADVANCE(54);
      if (lookahead == '{') ADVANCE(51);
      if (lookahead == '}') ADVANCE(52);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != ':') ADVANCE(74);
      END_STATE();
    case 38:
      if (eof) ADVANCE(39);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(38)
      if (lookahead == '%') ADVANCE(1);
      if (lookahead == ')') ADVANCE(56);
      if (lookahead == '_') ADVANCE(42);
      if (!sym_id_character_set_1(lookahead)) ADVANCE(74);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym__);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym__);
      if (!sym_id_character_set_2(lookahead)) ADVANCE(74);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (!sym_id_character_set_2(lookahead)) ADVANCE(74);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_PERCENTdefine);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_PERCENTsolve);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      if (!sym_id_character_set_2(lookahead)) ADVANCE(74);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_LT_DASH);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_LT_DASH);
      if (!sym_id_character_set_2(lookahead)) ADVANCE(74);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_type);
      if (!sym_id_character_set_2(lookahead)) ADVANCE(74);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_PERCENTmode);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_PERCENTtotal);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_PERCENTworlds);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_PERCENTfreeze);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(68);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_id);
      if (lookahead == '-') ADVANCE(50);
      if (!sym_id_character_set_2(lookahead)) ADVANCE(74);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_id);
      if (lookahead == '>') ADVANCE(48);
      if (!sym_id_character_set_2(lookahead)) ADVANCE(74);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_id);
      if (lookahead == 'e') ADVANCE(58);
      if (!sym_id_character_set_2(lookahead)) ADVANCE(74);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_id);
      if (lookahead == 'p') ADVANCE(71);
      if (!sym_id_character_set_2(lookahead)) ADVANCE(74);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_id);
      if (lookahead == 'y') ADVANCE(72);
      if (!sym_id_character_set_2(lookahead)) ADVANCE(74);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_id);
      if (!sym_id_character_set_2(lookahead)) ADVANCE(74);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 38},
  [2] = {.lex_state = 34},
  [3] = {.lex_state = 34},
  [4] = {.lex_state = 34},
  [5] = {.lex_state = 34},
  [6] = {.lex_state = 34},
  [7] = {.lex_state = 34},
  [8] = {.lex_state = 34},
  [9] = {.lex_state = 34},
  [10] = {.lex_state = 38},
  [11] = {.lex_state = 38},
  [12] = {.lex_state = 34},
  [13] = {.lex_state = 34},
  [14] = {.lex_state = 35},
  [15] = {.lex_state = 35},
  [16] = {.lex_state = 35},
  [17] = {.lex_state = 35},
  [18] = {.lex_state = 35},
  [19] = {.lex_state = 35},
  [20] = {.lex_state = 35},
  [21] = {.lex_state = 35},
  [22] = {.lex_state = 35},
  [23] = {.lex_state = 34},
  [24] = {.lex_state = 34},
  [25] = {.lex_state = 34},
  [26] = {.lex_state = 34},
  [27] = {.lex_state = 34},
  [28] = {.lex_state = 34},
  [29] = {.lex_state = 34},
  [30] = {.lex_state = 34},
  [31] = {.lex_state = 35},
  [32] = {.lex_state = 34},
  [33] = {.lex_state = 34},
  [34] = {.lex_state = 34},
  [35] = {.lex_state = 34},
  [36] = {.lex_state = 36},
  [37] = {.lex_state = 36},
  [38] = {.lex_state = 36},
  [39] = {.lex_state = 36},
  [40] = {.lex_state = 36},
  [41] = {.lex_state = 36},
  [42] = {.lex_state = 36},
  [43] = {.lex_state = 36},
  [44] = {.lex_state = 36},
  [45] = {.lex_state = 36},
  [46] = {.lex_state = 36},
  [47] = {.lex_state = 36},
  [48] = {.lex_state = 36},
  [49] = {.lex_state = 36},
  [50] = {.lex_state = 36},
  [51] = {.lex_state = 36},
  [52] = {.lex_state = 36},
  [53] = {.lex_state = 36},
  [54] = {.lex_state = 36},
  [55] = {.lex_state = 36},
  [56] = {.lex_state = 36},
  [57] = {.lex_state = 36},
  [58] = {.lex_state = 36},
  [59] = {.lex_state = 36},
  [60] = {.lex_state = 36},
  [61] = {.lex_state = 36},
  [62] = {.lex_state = 36},
  [63] = {.lex_state = 36},
  [64] = {.lex_state = 35},
  [65] = {.lex_state = 35},
  [66] = {.lex_state = 38},
  [67] = {.lex_state = 37},
  [68] = {.lex_state = 37},
  [69] = {.lex_state = 37},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 37},
  [72] = {.lex_state = 37},
  [73] = {.lex_state = 37},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 37},
  [76] = {.lex_state = 37},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 37},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 38},
  [81] = {.lex_state = 38},
  [82] = {.lex_state = 38},
  [83] = {.lex_state = 37},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 37},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 37},
  [91] = {.lex_state = 37},
  [92] = {.lex_state = 37},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 37},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 37},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 37},
  [105] = {.lex_state = 37},
  [106] = {.lex_state = 37},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 37},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 37},
  [111] = {.lex_state = 38},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 37},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 38},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 37},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 37},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 37},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 37},
  [131] = {.lex_state = 37},
  [132] = {.lex_state = 37},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 37},
  [136] = {.lex_state = 37},
  [137] = {.lex_state = 37},
  [138] = {.lex_state = 37},
  [139] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_PERCENTdefine] = ACTIONS(1),
    [anon_sym_PERCENTsolve] = ACTIONS(1),
    [anon_sym_LT_DASH] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_PERCENTmode] = ACTIONS(1),
    [anon_sym_PERCENTtotal] = ACTIONS(1),
    [anon_sym_PERCENTworlds] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_PERCENTfreeze] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(129),
    [sym__declaration] = STATE(11),
    [sym_con_decl] = STATE(128),
    [sym_defn] = STATE(128),
    [sym__solve_defn] = STATE(85),
    [sym_solve_decl] = STATE(128),
    [sym_mode_decl] = STATE(128),
    [sym_total_decl] = STATE(128),
    [sym_worlds_decl] = STATE(128),
    [sym_freeze_decl] = STATE(128),
    [aux_sym_source_file_repeat1] = STATE(11),
    [aux_sym_solve_decl_repeat1] = STATE(85),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym__] = ACTIONS(7),
    [anon_sym_PERCENTdefine] = ACTIONS(9),
    [anon_sym_PERCENTsolve] = ACTIONS(11),
    [anon_sym_PERCENTmode] = ACTIONS(13),
    [anon_sym_PERCENTtotal] = ACTIONS(15),
    [anon_sym_PERCENTworlds] = ACTIONS(17),
    [anon_sym_PERCENTfreeze] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
    [sym_id] = ACTIONS(21),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 2,
      anon_sym_DASH_GT,
      anon_sym_LT_DASH,
    ACTIONS(35), 2,
      anon_sym_type,
      sym_id,
    ACTIONS(23), 7,
      anon_sym_DOT,
      anon_sym_COLON,
      anon_sym_PERCENTdefine,
      anon_sym_PERCENTsolve,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
    STATE(3), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [42] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(39), 5,
      anon_sym__,
      anon_sym_DASH_GT,
      anon_sym_LT_DASH,
      anon_sym_type,
      sym_id,
    STATE(3), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
    ACTIONS(37), 10,
      anon_sym_DOT,
      anon_sym_COLON,
      anon_sym_PERCENTdefine,
      anon_sym_PERCENTsolve,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [74] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      anon_sym_COLON,
    ACTIONS(45), 1,
      anon_sym_DASH_GT,
    ACTIONS(47), 1,
      anon_sym_LT_DASH,
    ACTIONS(35), 2,
      anon_sym_type,
      sym_id,
    ACTIONS(41), 6,
      anon_sym_DOT,
      anon_sym_PERCENTdefine,
      anon_sym_PERCENTsolve,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
    STATE(3), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [120] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 2,
      anon_sym_type,
      sym_id,
    ACTIONS(51), 2,
      anon_sym_DASH_GT,
      anon_sym_LT_DASH,
    ACTIONS(49), 7,
      anon_sym_DOT,
      anon_sym_COLON,
      anon_sym_PERCENTdefine,
      anon_sym_PERCENTsolve,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
    STATE(3), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [162] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      anon_sym_COLON,
    ACTIONS(45), 1,
      anon_sym_DASH_GT,
    ACTIONS(47), 1,
      anon_sym_LT_DASH,
    ACTIONS(35), 2,
      anon_sym_type,
      sym_id,
    ACTIONS(53), 6,
      anon_sym_DOT,
      anon_sym_PERCENTdefine,
      anon_sym_PERCENTsolve,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
    STATE(3), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [208] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      anon_sym_COLON,
    ACTIONS(45), 1,
      anon_sym_DASH_GT,
    ACTIONS(47), 1,
      anon_sym_LT_DASH,
    ACTIONS(35), 2,
      anon_sym_type,
      sym_id,
    ACTIONS(55), 6,
      anon_sym_DOT,
      anon_sym_PERCENTdefine,
      anon_sym_PERCENTsolve,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
    STATE(3), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [254] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      anon_sym_COLON,
    ACTIONS(45), 1,
      anon_sym_DASH_GT,
    ACTIONS(47), 1,
      anon_sym_LT_DASH,
    ACTIONS(35), 2,
      anon_sym_type,
      sym_id,
    ACTIONS(57), 6,
      anon_sym_DOT,
      anon_sym_PERCENTdefine,
      anon_sym_PERCENTsolve,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
    STATE(3), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [300] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      anon_sym_COLON,
    ACTIONS(45), 1,
      anon_sym_DASH_GT,
    ACTIONS(47), 1,
      anon_sym_LT_DASH,
    ACTIONS(35), 2,
      anon_sym_type,
      sym_id,
    ACTIONS(59), 6,
      anon_sym_DOT,
      anon_sym_PERCENTdefine,
      anon_sym_PERCENTsolve,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
    STATE(3), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [346] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 1,
      ts_builtin_sym_end,
    ACTIONS(63), 1,
      anon_sym__,
    ACTIONS(66), 1,
      anon_sym_PERCENTdefine,
    ACTIONS(69), 1,
      anon_sym_PERCENTsolve,
    ACTIONS(72), 1,
      anon_sym_PERCENTmode,
    ACTIONS(75), 1,
      anon_sym_PERCENTtotal,
    ACTIONS(78), 1,
      anon_sym_PERCENTworlds,
    ACTIONS(81), 1,
      anon_sym_PERCENTfreeze,
    ACTIONS(84), 1,
      sym_id,
    STATE(10), 2,
      sym__declaration,
      aux_sym_source_file_repeat1,
    STATE(85), 2,
      sym__solve_defn,
      aux_sym_solve_decl_repeat1,
    STATE(128), 7,
      sym_con_decl,
      sym_defn,
      sym_solve_decl,
      sym_mode_decl,
      sym_total_decl,
      sym_worlds_decl,
      sym_freeze_decl,
  [394] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym__,
    ACTIONS(9), 1,
      anon_sym_PERCENTdefine,
    ACTIONS(11), 1,
      anon_sym_PERCENTsolve,
    ACTIONS(13), 1,
      anon_sym_PERCENTmode,
    ACTIONS(15), 1,
      anon_sym_PERCENTtotal,
    ACTIONS(17), 1,
      anon_sym_PERCENTworlds,
    ACTIONS(19), 1,
      anon_sym_PERCENTfreeze,
    ACTIONS(21), 1,
      sym_id,
    ACTIONS(87), 1,
      ts_builtin_sym_end,
    STATE(10), 2,
      sym__declaration,
      aux_sym_source_file_repeat1,
    STATE(85), 2,
      sym__solve_defn,
      aux_sym_solve_decl_repeat1,
    STATE(128), 7,
      sym_con_decl,
      sym_defn,
      sym_solve_decl,
      sym_mode_decl,
      sym_total_decl,
      sym_worlds_decl,
      sym_freeze_decl,
  [442] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      anon_sym_COLON,
    ACTIONS(45), 1,
      anon_sym_DASH_GT,
    ACTIONS(47), 1,
      anon_sym_LT_DASH,
    ACTIONS(35), 2,
      anon_sym_type,
      sym_id,
    ACTIONS(89), 3,
      anon_sym_DOT,
      anon_sym_PERCENTdefine,
      anon_sym_PERCENTsolve,
    STATE(3), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [485] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      anon_sym_COLON,
    ACTIONS(45), 1,
      anon_sym_DASH_GT,
    ACTIONS(47), 1,
      anon_sym_LT_DASH,
    ACTIONS(35), 2,
      anon_sym_type,
      sym_id,
    ACTIONS(91), 3,
      anon_sym_DOT,
      anon_sym_PERCENTdefine,
      anon_sym_PERCENTsolve,
    STATE(3), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [528] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_DOT,
    ACTIONS(95), 1,
      anon_sym__,
    ACTIONS(97), 1,
      anon_sym_COLON,
    ACTIONS(99), 1,
      anon_sym_EQ,
    ACTIONS(101), 1,
      anon_sym_DASH_GT,
    ACTIONS(103), 1,
      anon_sym_LT_DASH,
    ACTIONS(105), 1,
      anon_sym_LBRACE,
    ACTIONS(107), 1,
      anon_sym_LBRACK,
    ACTIONS(109), 1,
      anon_sym_LPAREN,
    ACTIONS(111), 2,
      anon_sym_type,
      sym_id,
    STATE(15), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [572] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 5,
      anon_sym_DOT,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
    ACTIONS(39), 6,
      anon_sym__,
      anon_sym_EQ,
      anon_sym_DASH_GT,
      anon_sym_LT_DASH,
      anon_sym_type,
      sym_id,
    STATE(15), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [600] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 1,
      anon_sym_DOT,
    ACTIONS(95), 1,
      anon_sym__,
    ACTIONS(97), 1,
      anon_sym_COLON,
    ACTIONS(101), 1,
      anon_sym_DASH_GT,
    ACTIONS(103), 1,
      anon_sym_LT_DASH,
    ACTIONS(105), 1,
      anon_sym_LBRACE,
    ACTIONS(107), 1,
      anon_sym_LBRACK,
    ACTIONS(109), 1,
      anon_sym_LPAREN,
    ACTIONS(113), 1,
      anon_sym_EQ,
    ACTIONS(111), 2,
      anon_sym_type,
      sym_id,
    STATE(15), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [644] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_DOT,
    ACTIONS(95), 1,
      anon_sym__,
    ACTIONS(97), 1,
      anon_sym_COLON,
    ACTIONS(101), 1,
      anon_sym_DASH_GT,
    ACTIONS(103), 1,
      anon_sym_LT_DASH,
    ACTIONS(105), 1,
      anon_sym_LBRACE,
    ACTIONS(107), 1,
      anon_sym_LBRACK,
    ACTIONS(109), 1,
      anon_sym_LPAREN,
    ACTIONS(115), 1,
      anon_sym_EQ,
    ACTIONS(111), 2,
      anon_sym_type,
      sym_id,
    STATE(15), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [688] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      anon_sym__,
    ACTIONS(105), 1,
      anon_sym_LBRACE,
    ACTIONS(107), 1,
      anon_sym_LBRACK,
    ACTIONS(109), 1,
      anon_sym_LPAREN,
    ACTIONS(49), 2,
      anon_sym_DOT,
      anon_sym_COLON,
    ACTIONS(111), 2,
      anon_sym_type,
      sym_id,
    ACTIONS(51), 3,
      anon_sym_EQ,
      anon_sym_DASH_GT,
      anon_sym_LT_DASH,
    STATE(15), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [726] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_DOT,
    ACTIONS(95), 1,
      anon_sym__,
    ACTIONS(97), 1,
      anon_sym_COLON,
    ACTIONS(101), 1,
      anon_sym_DASH_GT,
    ACTIONS(103), 1,
      anon_sym_LT_DASH,
    ACTIONS(105), 1,
      anon_sym_LBRACE,
    ACTIONS(107), 1,
      anon_sym_LBRACK,
    ACTIONS(109), 1,
      anon_sym_LPAREN,
    ACTIONS(117), 1,
      anon_sym_EQ,
    ACTIONS(111), 2,
      anon_sym_type,
      sym_id,
    STATE(15), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [770] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym_DOT,
    ACTIONS(95), 1,
      anon_sym__,
    ACTIONS(97), 1,
      anon_sym_COLON,
    ACTIONS(101), 1,
      anon_sym_DASH_GT,
    ACTIONS(103), 1,
      anon_sym_LT_DASH,
    ACTIONS(105), 1,
      anon_sym_LBRACE,
    ACTIONS(107), 1,
      anon_sym_LBRACK,
    ACTIONS(109), 1,
      anon_sym_LPAREN,
    ACTIONS(119), 1,
      anon_sym_EQ,
    ACTIONS(111), 2,
      anon_sym_type,
      sym_id,
    STATE(15), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [814] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      anon_sym__,
    ACTIONS(105), 1,
      anon_sym_LBRACE,
    ACTIONS(107), 1,
      anon_sym_LBRACK,
    ACTIONS(109), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 2,
      anon_sym_DOT,
      anon_sym_COLON,
    ACTIONS(111), 2,
      anon_sym_type,
      sym_id,
    ACTIONS(27), 3,
      anon_sym_EQ,
      anon_sym_DASH_GT,
      anon_sym_LT_DASH,
    STATE(15), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [852] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      anon_sym_DOT,
    ACTIONS(95), 1,
      anon_sym__,
    ACTIONS(97), 1,
      anon_sym_COLON,
    ACTIONS(101), 1,
      anon_sym_DASH_GT,
    ACTIONS(103), 1,
      anon_sym_LT_DASH,
    ACTIONS(105), 1,
      anon_sym_LBRACE,
    ACTIONS(107), 1,
      anon_sym_LBRACK,
    ACTIONS(109), 1,
      anon_sym_LPAREN,
    ACTIONS(121), 1,
      anon_sym_EQ,
    ACTIONS(111), 2,
      anon_sym_type,
      sym_id,
    STATE(15), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [896] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      anon_sym_COLON,
    ACTIONS(45), 1,
      anon_sym_DASH_GT,
    ACTIONS(47), 1,
      anon_sym_LT_DASH,
    ACTIONS(123), 1,
      anon_sym_RBRACE,
    ACTIONS(35), 2,
      anon_sym_type,
      sym_id,
    STATE(3), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [937] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      anon_sym_COLON,
    ACTIONS(45), 1,
      anon_sym_DASH_GT,
    ACTIONS(47), 1,
      anon_sym_LT_DASH,
    ACTIONS(125), 1,
      anon_sym_RPAREN,
    ACTIONS(35), 2,
      anon_sym_type,
      sym_id,
    STATE(3), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [978] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      anon_sym_COLON,
    ACTIONS(45), 1,
      anon_sym_DASH_GT,
    ACTIONS(47), 1,
      anon_sym_LT_DASH,
    ACTIONS(93), 1,
      anon_sym_DOT,
    ACTIONS(35), 2,
      anon_sym_type,
      sym_id,
    STATE(3), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1019] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      anon_sym_COLON,
    ACTIONS(45), 1,
      anon_sym_DASH_GT,
    ACTIONS(47), 1,
      anon_sym_LT_DASH,
    ACTIONS(127), 1,
      anon_sym_RPAREN,
    ACTIONS(35), 2,
      anon_sym_type,
      sym_id,
    STATE(3), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1060] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      anon_sym_COLON,
    ACTIONS(45), 1,
      anon_sym_DASH_GT,
    ACTIONS(47), 1,
      anon_sym_LT_DASH,
    ACTIONS(129), 1,
      anon_sym_DOT,
    ACTIONS(35), 2,
      anon_sym_type,
      sym_id,
    STATE(3), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1101] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      anon_sym_COLON,
    ACTIONS(45), 1,
      anon_sym_DASH_GT,
    ACTIONS(47), 1,
      anon_sym_LT_DASH,
    ACTIONS(131), 1,
      anon_sym_RBRACK,
    ACTIONS(35), 2,
      anon_sym_type,
      sym_id,
    STATE(3), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1142] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      anon_sym_COLON,
    ACTIONS(45), 1,
      anon_sym_DASH_GT,
    ACTIONS(47), 1,
      anon_sym_LT_DASH,
    ACTIONS(133), 1,
      anon_sym_DOT,
    ACTIONS(35), 2,
      anon_sym_type,
      sym_id,
    STATE(3), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1183] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      anon_sym_COLON,
    ACTIONS(45), 1,
      anon_sym_DASH_GT,
    ACTIONS(47), 1,
      anon_sym_LT_DASH,
    ACTIONS(135), 1,
      anon_sym_RBRACE,
    ACTIONS(35), 2,
      anon_sym_type,
      sym_id,
    STATE(3), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1224] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      anon_sym__,
    ACTIONS(97), 1,
      anon_sym_COLON,
    ACTIONS(99), 1,
      anon_sym_EQ,
    ACTIONS(101), 1,
      anon_sym_DASH_GT,
    ACTIONS(103), 1,
      anon_sym_LT_DASH,
    ACTIONS(105), 1,
      anon_sym_LBRACE,
    ACTIONS(107), 1,
      anon_sym_LBRACK,
    ACTIONS(109), 1,
      anon_sym_LPAREN,
    ACTIONS(111), 2,
      anon_sym_type,
      sym_id,
    STATE(15), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1265] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      anon_sym_COLON,
    ACTIONS(45), 1,
      anon_sym_DASH_GT,
    ACTIONS(47), 1,
      anon_sym_LT_DASH,
    ACTIONS(137), 1,
      anon_sym_RBRACK,
    ACTIONS(35), 2,
      anon_sym_type,
      sym_id,
    STATE(3), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1306] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      anon_sym_COLON,
    ACTIONS(45), 1,
      anon_sym_DASH_GT,
    ACTIONS(47), 1,
      anon_sym_LT_DASH,
    ACTIONS(139), 1,
      anon_sym_RBRACE,
    ACTIONS(35), 2,
      anon_sym_type,
      sym_id,
    STATE(3), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1347] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 5,
      anon_sym__,
      anon_sym_DASH_GT,
      anon_sym_LT_DASH,
      anon_sym_type,
      sym_id,
    ACTIONS(141), 10,
      anon_sym_DOT,
      anon_sym_COLON,
      anon_sym_PERCENTdefine,
      anon_sym_PERCENTsolve,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [1370] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 5,
      anon_sym__,
      anon_sym_DASH_GT,
      anon_sym_LT_DASH,
      anon_sym_type,
      sym_id,
    ACTIONS(145), 10,
      anon_sym_DOT,
      anon_sym_COLON,
      anon_sym_PERCENTdefine,
      anon_sym_PERCENTsolve,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [1393] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(149), 2,
      anon_sym_type,
      sym_id,
    STATE(4), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1422] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      anon_sym__,
    ACTIONS(105), 1,
      anon_sym_LBRACE,
    ACTIONS(107), 1,
      anon_sym_LBRACK,
    ACTIONS(109), 1,
      anon_sym_LPAREN,
    ACTIONS(151), 2,
      anon_sym_type,
      sym_id,
    STATE(21), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1451] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 2,
      anon_sym_type,
      sym_id,
    STATE(24), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1480] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      anon_sym__,
    ACTIONS(105), 1,
      anon_sym_LBRACE,
    ACTIONS(107), 1,
      anon_sym_LBRACK,
    ACTIONS(109), 1,
      anon_sym_LPAREN,
    ACTIONS(155), 2,
      anon_sym_type,
      sym_id,
    STATE(31), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1509] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(157), 2,
      anon_sym_type,
      sym_id,
    STATE(27), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1538] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(159), 2,
      anon_sym_type,
      sym_id,
    STATE(28), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1567] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      anon_sym__,
    ACTIONS(105), 1,
      anon_sym_LBRACE,
    ACTIONS(107), 1,
      anon_sym_LBRACK,
    ACTIONS(109), 1,
      anon_sym_LPAREN,
    ACTIONS(161), 2,
      anon_sym_type,
      sym_id,
    STATE(20), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1596] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(163), 2,
      anon_sym_type,
      sym_id,
    STATE(9), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1625] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(165), 2,
      anon_sym_type,
      sym_id,
    STATE(7), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1654] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(167), 2,
      anon_sym_type,
      sym_id,
    STATE(8), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1683] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(169), 2,
      anon_sym_type,
      sym_id,
    STATE(32), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1712] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(171), 2,
      anon_sym_type,
      sym_id,
    STATE(23), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1741] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(173), 2,
      anon_sym_type,
      sym_id,
    STATE(6), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1770] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(175), 2,
      anon_sym_type,
      sym_id,
    STATE(30), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1799] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      anon_sym__,
    ACTIONS(105), 1,
      anon_sym_LBRACE,
    ACTIONS(107), 1,
      anon_sym_LBRACK,
    ACTIONS(109), 1,
      anon_sym_LPAREN,
    ACTIONS(177), 2,
      anon_sym_type,
      sym_id,
    STATE(22), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1828] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(179), 2,
      anon_sym_type,
      sym_id,
    STATE(13), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1857] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      anon_sym__,
    ACTIONS(105), 1,
      anon_sym_LBRACE,
    ACTIONS(107), 1,
      anon_sym_LBRACK,
    ACTIONS(109), 1,
      anon_sym_LPAREN,
    ACTIONS(181), 2,
      anon_sym_type,
      sym_id,
    STATE(19), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1886] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      anon_sym__,
    ACTIONS(105), 1,
      anon_sym_LBRACE,
    ACTIONS(107), 1,
      anon_sym_LBRACK,
    ACTIONS(109), 1,
      anon_sym_LPAREN,
    ACTIONS(183), 2,
      anon_sym_type,
      sym_id,
    STATE(18), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1915] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(185), 2,
      anon_sym_type,
      sym_id,
    STATE(26), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1944] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(187), 2,
      anon_sym_type,
      sym_id,
    STATE(12), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1973] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      anon_sym__,
    ACTIONS(105), 1,
      anon_sym_LBRACE,
    ACTIONS(107), 1,
      anon_sym_LBRACK,
    ACTIONS(109), 1,
      anon_sym_LPAREN,
    ACTIONS(189), 2,
      anon_sym_type,
      sym_id,
    STATE(14), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [2002] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      anon_sym__,
    ACTIONS(105), 1,
      anon_sym_LBRACE,
    ACTIONS(107), 1,
      anon_sym_LBRACK,
    ACTIONS(109), 1,
      anon_sym_LPAREN,
    ACTIONS(191), 2,
      anon_sym_type,
      sym_id,
    STATE(17), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [2031] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(193), 2,
      anon_sym_type,
      sym_id,
    STATE(33), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [2060] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      anon_sym__,
    ACTIONS(105), 1,
      anon_sym_LBRACE,
    ACTIONS(107), 1,
      anon_sym_LBRACK,
    ACTIONS(109), 1,
      anon_sym_LPAREN,
    ACTIONS(195), 2,
      anon_sym_type,
      sym_id,
    STATE(16), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [2089] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(197), 2,
      anon_sym_type,
      sym_id,
    STATE(29), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [2118] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(199), 2,
      anon_sym_type,
      sym_id,
    STATE(2), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [2147] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(201), 2,
      anon_sym_type,
      sym_id,
    STATE(25), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [2176] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(203), 2,
      anon_sym_type,
      sym_id,
    STATE(5), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [2205] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 5,
      anon_sym_DOT,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
    ACTIONS(143), 6,
      anon_sym__,
      anon_sym_EQ,
      anon_sym_DASH_GT,
      anon_sym_LT_DASH,
      anon_sym_type,
      sym_id,
  [2224] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 5,
      anon_sym_DOT,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
    ACTIONS(147), 6,
      anon_sym__,
      anon_sym_EQ,
      anon_sym_DASH_GT,
      anon_sym_LT_DASH,
      anon_sym_type,
      sym_id,
  [2243] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 2,
      anon_sym__,
      sym_id,
    ACTIONS(205), 7,
      ts_builtin_sym_end,
      anon_sym_PERCENTdefine,
      anon_sym_PERCENTsolve,
      anon_sym_PERCENTmode,
      anon_sym_PERCENTtotal,
      anon_sym_PERCENTworlds,
      anon_sym_PERCENTfreeze,
  [2260] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 1,
      anon_sym_LBRACE,
    ACTIONS(214), 1,
      anon_sym_LBRACK,
    ACTIONS(217), 1,
      anon_sym_LPAREN,
    ACTIONS(220), 1,
      sym_id,
    ACTIONS(212), 2,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
    STATE(67), 2,
      sym_order,
      aux_sym_order_repeat1,
  [2284] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 7,
      anon_sym_DOT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      sym_id,
  [2297] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 1,
      anon_sym_LBRACE,
    ACTIONS(227), 1,
      anon_sym_LBRACK,
    ACTIONS(229), 1,
      anon_sym_RBRACK,
    ACTIONS(231), 1,
      anon_sym_LPAREN,
    ACTIONS(233), 1,
      sym_id,
    STATE(75), 2,
      sym_order,
      aux_sym_order_repeat1,
  [2320] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 1,
      anon_sym_DOT,
    STATE(138), 1,
      sym_mode,
    STATE(70), 2,
      sym_mid,
      aux_sym_mode_decl_repeat1,
    ACTIONS(237), 3,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_DASH,
  [2339] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 7,
      anon_sym_DOT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      sym_id,
  [2352] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 1,
      anon_sym_LBRACE,
    ACTIONS(227), 1,
      anon_sym_LBRACK,
    ACTIONS(229), 1,
      anon_sym_RBRACE,
    ACTIONS(231), 1,
      anon_sym_LPAREN,
    ACTIONS(233), 1,
      sym_id,
    STATE(76), 2,
      sym_order,
      aux_sym_order_repeat1,
  [2375] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(242), 7,
      anon_sym_DOT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      sym_id,
  [2388] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 1,
      anon_sym_DOT,
    STATE(138), 1,
      sym_mode,
    STATE(70), 2,
      sym_mid,
      aux_sym_mode_decl_repeat1,
    ACTIONS(246), 3,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_DASH,
  [2407] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 1,
      anon_sym_LBRACE,
    ACTIONS(227), 1,
      anon_sym_LBRACK,
    ACTIONS(231), 1,
      anon_sym_LPAREN,
    ACTIONS(233), 1,
      sym_id,
    ACTIONS(248), 1,
      anon_sym_RBRACK,
    STATE(67), 2,
      sym_order,
      aux_sym_order_repeat1,
  [2430] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 1,
      anon_sym_LBRACE,
    ACTIONS(227), 1,
      anon_sym_LBRACK,
    ACTIONS(231), 1,
      anon_sym_LPAREN,
    ACTIONS(233), 1,
      sym_id,
    ACTIONS(248), 1,
      anon_sym_RBRACE,
    STATE(67), 2,
      sym_order,
      aux_sym_order_repeat1,
  [2453] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 1,
      anon_sym_DOT,
    STATE(138), 1,
      sym_mode,
    STATE(74), 2,
      sym_mid,
      aux_sym_mode_decl_repeat1,
    ACTIONS(246), 3,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_DASH,
  [2472] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 1,
      anon_sym_LBRACE,
    ACTIONS(227), 1,
      anon_sym_LBRACK,
    ACTIONS(231), 1,
      anon_sym_LPAREN,
    ACTIONS(233), 1,
      sym_id,
    STATE(93), 1,
      sym_order,
  [2491] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 4,
      anon_sym_DOT,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_DASH,
  [2501] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 1,
      anon_sym_RPAREN,
    STATE(81), 1,
      aux_sym_callpat_repeat1,
    ACTIONS(254), 2,
      anon_sym__,
      sym_id,
  [2515] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 1,
      anon_sym_RPAREN,
    STATE(81), 1,
      aux_sym_callpat_repeat1,
    ACTIONS(258), 2,
      anon_sym__,
      sym_id,
  [2529] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 1,
      anon_sym_RPAREN,
    STATE(80), 1,
      aux_sym_callpat_repeat1,
    ACTIONS(263), 2,
      anon_sym__,
      sym_id,
  [2543] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 1,
      sym_id,
    STATE(83), 1,
      aux_sym_mode_decl_repeat3,
    ACTIONS(267), 2,
      anon_sym_DOT,
      anon_sym_RPAREN,
  [2557] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(272), 1,
      anon_sym_PERCENTdefine,
    ACTIONS(275), 1,
      anon_sym_PERCENTsolve,
    STATE(84), 2,
      sym__solve_defn,
      aux_sym_solve_decl_repeat1,
  [2571] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_PERCENTdefine,
    ACTIONS(277), 1,
      anon_sym_PERCENTsolve,
    STATE(84), 2,
      sym__solve_defn,
      aux_sym_solve_decl_repeat1,
  [2585] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(132), 1,
      sym_mode,
    ACTIONS(246), 3,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_DASH,
  [2597] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(279), 1,
      anon_sym_DOT,
    ACTIONS(281), 1,
      sym_id,
    STATE(83), 1,
      aux_sym_mode_decl_repeat3,
  [2610] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      anon_sym_DOT,
    ACTIONS(285), 1,
      anon_sym_LPAREN,
    STATE(100), 1,
      aux_sym_total_decl_repeat1,
  [2623] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      anon_sym_DOT,
    ACTIONS(285), 1,
      anon_sym_LPAREN,
    STATE(95), 1,
      aux_sym_total_decl_repeat1,
  [2636] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(287), 1,
      anon_sym_DOT,
    ACTIONS(289), 1,
      sym_id,
    STATE(87), 1,
      aux_sym_mode_decl_repeat3,
  [2649] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(291), 1,
      anon_sym_LBRACE,
    ACTIONS(293), 1,
      sym_id,
    STATE(94), 1,
      aux_sym_mode_decl_repeat2,
  [2662] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 1,
      anon_sym_RPAREN,
    ACTIONS(295), 1,
      sym_id,
    STATE(105), 1,
      aux_sym_mode_decl_repeat3,
  [2675] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(285), 1,
      anon_sym_LPAREN,
    ACTIONS(297), 1,
      anon_sym_DOT,
    STATE(103), 1,
      aux_sym_total_decl_repeat1,
  [2688] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(299), 1,
      anon_sym_LBRACE,
    ACTIONS(302), 1,
      sym_id,
    STATE(94), 1,
      aux_sym_mode_decl_repeat2,
  [2701] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(285), 1,
      anon_sym_LPAREN,
    ACTIONS(304), 1,
      anon_sym_DOT,
    STATE(100), 1,
      aux_sym_total_decl_repeat1,
  [2714] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 1,
      sym_id,
    ACTIONS(306), 1,
      anon_sym_DOT,
    STATE(83), 1,
      aux_sym_mode_decl_repeat3,
  [2727] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(285), 1,
      anon_sym_LPAREN,
    ACTIONS(304), 1,
      anon_sym_DOT,
    STATE(107), 1,
      aux_sym_total_decl_repeat1,
  [2740] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(308), 1,
      anon_sym_RPAREN,
    ACTIONS(310), 1,
      anon_sym_PIPE,
    STATE(98), 1,
      aux_sym_worlds_decl_repeat1,
  [2753] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(313), 1,
      anon_sym_RPAREN,
    ACTIONS(315), 1,
      anon_sym_PIPE,
    STATE(98), 1,
      aux_sym_worlds_decl_repeat1,
  [2766] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(317), 1,
      anon_sym_DOT,
    ACTIONS(319), 1,
      anon_sym_LPAREN,
    STATE(100), 1,
      aux_sym_total_decl_repeat1,
  [2779] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(315), 1,
      anon_sym_PIPE,
    ACTIONS(322), 1,
      anon_sym_RPAREN,
    STATE(99), 1,
      aux_sym_worlds_decl_repeat1,
  [2792] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(285), 1,
      anon_sym_LPAREN,
    ACTIONS(324), 1,
      anon_sym_DOT,
    STATE(88), 1,
      aux_sym_total_decl_repeat1,
  [2805] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(285), 1,
      anon_sym_LPAREN,
    ACTIONS(326), 1,
      anon_sym_DOT,
    STATE(100), 1,
      aux_sym_total_decl_repeat1,
  [2818] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 1,
      anon_sym_DOT,
    ACTIONS(328), 1,
      sym_id,
    STATE(96), 1,
      aux_sym_mode_decl_repeat3,
  [2831] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 1,
      anon_sym_RPAREN,
    ACTIONS(281), 1,
      sym_id,
    STATE(83), 1,
      aux_sym_mode_decl_repeat3,
  [2844] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(291), 1,
      anon_sym_LBRACE,
    ACTIONS(330), 1,
      sym_id,
    STATE(91), 1,
      aux_sym_mode_decl_repeat2,
  [2857] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(285), 1,
      anon_sym_LPAREN,
    ACTIONS(332), 1,
      anon_sym_DOT,
    STATE(100), 1,
      aux_sym_total_decl_repeat1,
  [2870] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(334), 2,
      anon_sym_LBRACE,
      sym_id,
  [2878] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(336), 1,
      anon_sym_COLON,
    ACTIONS(338), 1,
      anon_sym_RBRACE,
  [2888] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(340), 1,
      sym_id,
    STATE(124), 1,
      sym_defn,
  [2898] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(342), 2,
      anon_sym__,
      sym_id,
  [2906] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(344), 1,
      anon_sym_COLON,
    ACTIONS(346), 1,
      anon_sym_EQ,
  [2916] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(348), 1,
      anon_sym_COLON,
    ACTIONS(350), 1,
      anon_sym_RBRACK,
  [2926] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(352), 1,
      sym_id,
    STATE(139), 1,
      sym_callpat,
  [2936] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(354), 1,
      anon_sym_COLON,
    ACTIONS(356), 1,
      anon_sym_RBRACE,
  [2946] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(346), 1,
      anon_sym_EQ,
    ACTIONS(358), 1,
      anon_sym_COLON,
  [2956] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(360), 2,
      anon_sym__,
      sym_id,
  [2964] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(308), 2,
      anon_sym_RPAREN,
      anon_sym_PIPE,
  [2972] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(362), 1,
      anon_sym_RPAREN,
    ACTIONS(364), 1,
      sym_id,
  [2982] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(366), 2,
      anon_sym_DOT,
      anon_sym_LPAREN,
  [2990] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(368), 2,
      anon_sym_LBRACE,
      sym_id,
  [2998] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(370), 1,
      anon_sym_COLON,
    ACTIONS(372), 1,
      anon_sym_RBRACE,
  [3008] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(374), 1,
      anon_sym_COLON,
    ACTIONS(376), 1,
      anon_sym_RBRACK,
  [3018] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(378), 2,
      anon_sym_PERCENTdefine,
      anon_sym_PERCENTsolve,
  [3026] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(380), 1,
      anon_sym_COLON,
  [3033] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(382), 1,
      anon_sym_COLON,
  [3040] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(384), 1,
      sym_id,
  [3047] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(386), 1,
      anon_sym_DOT,
  [3054] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(388), 1,
      ts_builtin_sym_end,
  [3061] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(390), 1,
      sym_id,
  [3068] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(392), 1,
      sym_id,
  [3075] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(394), 1,
      sym_id,
  [3082] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(396), 1,
      anon_sym_COLON,
  [3089] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(398), 1,
      anon_sym_LPAREN,
  [3096] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(400), 1,
      sym_id,
  [3103] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(402), 1,
      sym_id,
  [3110] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(404), 1,
      sym_id,
  [3117] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(406), 1,
      sym_id,
  [3124] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(408), 1,
      anon_sym_RPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 42,
  [SMALL_STATE(4)] = 74,
  [SMALL_STATE(5)] = 120,
  [SMALL_STATE(6)] = 162,
  [SMALL_STATE(7)] = 208,
  [SMALL_STATE(8)] = 254,
  [SMALL_STATE(9)] = 300,
  [SMALL_STATE(10)] = 346,
  [SMALL_STATE(11)] = 394,
  [SMALL_STATE(12)] = 442,
  [SMALL_STATE(13)] = 485,
  [SMALL_STATE(14)] = 528,
  [SMALL_STATE(15)] = 572,
  [SMALL_STATE(16)] = 600,
  [SMALL_STATE(17)] = 644,
  [SMALL_STATE(18)] = 688,
  [SMALL_STATE(19)] = 726,
  [SMALL_STATE(20)] = 770,
  [SMALL_STATE(21)] = 814,
  [SMALL_STATE(22)] = 852,
  [SMALL_STATE(23)] = 896,
  [SMALL_STATE(24)] = 937,
  [SMALL_STATE(25)] = 978,
  [SMALL_STATE(26)] = 1019,
  [SMALL_STATE(27)] = 1060,
  [SMALL_STATE(28)] = 1101,
  [SMALL_STATE(29)] = 1142,
  [SMALL_STATE(30)] = 1183,
  [SMALL_STATE(31)] = 1224,
  [SMALL_STATE(32)] = 1265,
  [SMALL_STATE(33)] = 1306,
  [SMALL_STATE(34)] = 1347,
  [SMALL_STATE(35)] = 1370,
  [SMALL_STATE(36)] = 1393,
  [SMALL_STATE(37)] = 1422,
  [SMALL_STATE(38)] = 1451,
  [SMALL_STATE(39)] = 1480,
  [SMALL_STATE(40)] = 1509,
  [SMALL_STATE(41)] = 1538,
  [SMALL_STATE(42)] = 1567,
  [SMALL_STATE(43)] = 1596,
  [SMALL_STATE(44)] = 1625,
  [SMALL_STATE(45)] = 1654,
  [SMALL_STATE(46)] = 1683,
  [SMALL_STATE(47)] = 1712,
  [SMALL_STATE(48)] = 1741,
  [SMALL_STATE(49)] = 1770,
  [SMALL_STATE(50)] = 1799,
  [SMALL_STATE(51)] = 1828,
  [SMALL_STATE(52)] = 1857,
  [SMALL_STATE(53)] = 1886,
  [SMALL_STATE(54)] = 1915,
  [SMALL_STATE(55)] = 1944,
  [SMALL_STATE(56)] = 1973,
  [SMALL_STATE(57)] = 2002,
  [SMALL_STATE(58)] = 2031,
  [SMALL_STATE(59)] = 2060,
  [SMALL_STATE(60)] = 2089,
  [SMALL_STATE(61)] = 2118,
  [SMALL_STATE(62)] = 2147,
  [SMALL_STATE(63)] = 2176,
  [SMALL_STATE(64)] = 2205,
  [SMALL_STATE(65)] = 2224,
  [SMALL_STATE(66)] = 2243,
  [SMALL_STATE(67)] = 2260,
  [SMALL_STATE(68)] = 2284,
  [SMALL_STATE(69)] = 2297,
  [SMALL_STATE(70)] = 2320,
  [SMALL_STATE(71)] = 2339,
  [SMALL_STATE(72)] = 2352,
  [SMALL_STATE(73)] = 2375,
  [SMALL_STATE(74)] = 2388,
  [SMALL_STATE(75)] = 2407,
  [SMALL_STATE(76)] = 2430,
  [SMALL_STATE(77)] = 2453,
  [SMALL_STATE(78)] = 2472,
  [SMALL_STATE(79)] = 2491,
  [SMALL_STATE(80)] = 2501,
  [SMALL_STATE(81)] = 2515,
  [SMALL_STATE(82)] = 2529,
  [SMALL_STATE(83)] = 2543,
  [SMALL_STATE(84)] = 2557,
  [SMALL_STATE(85)] = 2571,
  [SMALL_STATE(86)] = 2585,
  [SMALL_STATE(87)] = 2597,
  [SMALL_STATE(88)] = 2610,
  [SMALL_STATE(89)] = 2623,
  [SMALL_STATE(90)] = 2636,
  [SMALL_STATE(91)] = 2649,
  [SMALL_STATE(92)] = 2662,
  [SMALL_STATE(93)] = 2675,
  [SMALL_STATE(94)] = 2688,
  [SMALL_STATE(95)] = 2701,
  [SMALL_STATE(96)] = 2714,
  [SMALL_STATE(97)] = 2727,
  [SMALL_STATE(98)] = 2740,
  [SMALL_STATE(99)] = 2753,
  [SMALL_STATE(100)] = 2766,
  [SMALL_STATE(101)] = 2779,
  [SMALL_STATE(102)] = 2792,
  [SMALL_STATE(103)] = 2805,
  [SMALL_STATE(104)] = 2818,
  [SMALL_STATE(105)] = 2831,
  [SMALL_STATE(106)] = 2844,
  [SMALL_STATE(107)] = 2857,
  [SMALL_STATE(108)] = 2870,
  [SMALL_STATE(109)] = 2878,
  [SMALL_STATE(110)] = 2888,
  [SMALL_STATE(111)] = 2898,
  [SMALL_STATE(112)] = 2906,
  [SMALL_STATE(113)] = 2916,
  [SMALL_STATE(114)] = 2926,
  [SMALL_STATE(115)] = 2936,
  [SMALL_STATE(116)] = 2946,
  [SMALL_STATE(117)] = 2956,
  [SMALL_STATE(118)] = 2964,
  [SMALL_STATE(119)] = 2972,
  [SMALL_STATE(120)] = 2982,
  [SMALL_STATE(121)] = 2990,
  [SMALL_STATE(122)] = 2998,
  [SMALL_STATE(123)] = 3008,
  [SMALL_STATE(124)] = 3018,
  [SMALL_STATE(125)] = 3026,
  [SMALL_STATE(126)] = 3033,
  [SMALL_STATE(127)] = 3040,
  [SMALL_STATE(128)] = 3047,
  [SMALL_STATE(129)] = 3054,
  [SMALL_STATE(130)] = 3061,
  [SMALL_STATE(131)] = 3068,
  [SMALL_STATE(132)] = 3075,
  [SMALL_STATE(133)] = 3082,
  [SMALL_STATE(134)] = 3089,
  [SMALL_STATE(135)] = 3096,
  [SMALL_STATE(136)] = 3103,
  [SMALL_STATE(137)] = 3110,
  [SMALL_STATE(138)] = 3117,
  [SMALL_STATE(139)] = 3124,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(133),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(112),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tm_ascrip, 3),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tm_ascrip, 3),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tm_app, 2),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tm_app, 2),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tm_fun, 3, .production_id = 2),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tm_fun, 3, .production_id = 3),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tm_fun, 3, .production_id = 3),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tm_pi, 4),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tm_lam, 4),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tm_pi, 6),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tm_lam, 6),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [63] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(133),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(110),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(111),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(106),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(78),
  [78] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(134),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(90),
  [84] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(112),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_defn, 3),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_defn, 5),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_con_decl, 3),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [99] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tm_lam, 4),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tm_pi, 4),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tm_fun, 3, .production_id = 2),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tm_pi, 6),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tm_lam, 6),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_solve_decl, 4),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_solve_decl, 5),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tm_bracket, 3),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tm_bracket, 3),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__term, 1, .production_id = 1),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__term, 1, .production_id = 1),
  [149] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [151] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [153] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [155] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [157] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [159] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [161] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [163] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [165] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [167] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [169] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [171] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [173] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [175] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [177] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [179] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [181] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [183] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [185] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [187] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [189] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [191] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [193] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [195] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [197] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [199] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [201] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [203] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__declaration, 2),
  [207] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__declaration, 2),
  [209] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_order_repeat1, 2), SHIFT_REPEAT(72),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_order_repeat1, 2),
  [214] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_order_repeat1, 2), SHIFT_REPEAT(69),
  [217] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_order_repeat1, 2), SHIFT_REPEAT(92),
  [220] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_order_repeat1, 2), SHIFT_REPEAT(73),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_order, 2),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_mode_decl_repeat1, 2),
  [237] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_mode_decl_repeat1, 2), SHIFT_REPEAT(131),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_order, 3),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_order, 1),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mode_decl, 3),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mode_decl, 2),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mid, 2),
  [254] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_callpat, 2),
  [258] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_callpat_repeat1, 2), SHIFT_REPEAT(81),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_callpat_repeat1, 2),
  [263] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_callpat, 1),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_mode_decl_repeat3, 2),
  [269] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_mode_decl_repeat3, 2), SHIFT_REPEAT(83),
  [272] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_solve_decl_repeat1, 2), SHIFT_REPEAT(110),
  [275] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_solve_decl_repeat1, 2),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_freeze_decl, 2),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [283] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_worlds_decl, 4),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [287] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_freeze_decl, 1),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [297] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_total_decl, 2),
  [299] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_mode_decl_repeat2, 2), SHIFT_REPEAT(86),
  [302] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_mode_decl_repeat2, 2),
  [304] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_worlds_decl, 5),
  [306] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mode_decl, 4),
  [308] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_worlds_decl_repeat1, 2),
  [310] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_worlds_decl_repeat1, 2), SHIFT_REPEAT(137),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [317] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_total_decl_repeat1, 2),
  [319] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_total_decl_repeat1, 2), SHIFT_REPEAT(114),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [324] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_worlds_decl, 3),
  [326] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_total_decl, 3),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [332] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_worlds_decl, 6),
  [334] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_mode_decl_repeat2, 6),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [342] = {.entry = {.count = 1, .reusable = false}}, SHIFT(125),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [350] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [352] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [354] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [356] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [358] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [360] = {.entry = {.count = 1, .reusable = false}}, SHIFT(126),
  [362] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [364] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [366] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_total_decl_repeat1, 3),
  [368] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_mode_decl_repeat2, 4),
  [370] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [372] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [374] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [376] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [378] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__solve_defn, 2),
  [380] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [382] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [384] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [386] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [388] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [390] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [392] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mode, 1),
  [394] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [396] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [398] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [400] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [402] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [404] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [406] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [408] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_twelf(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
