#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 127
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 51
#define ALIAS_COUNT 1
#define TOKEN_COUNT 24
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 4

enum {
  anon_sym_DOT = 1,
  anon_sym__ = 2,
  anon_sym_COLON = 3,
  anon_sym_EQ = 4,
  anon_sym_PERCENTsolve = 5,
  anon_sym_DASH_GT = 6,
  anon_sym_LT_DASH = 7,
  anon_sym_LBRACE = 8,
  anon_sym_RBRACE = 9,
  anon_sym_LBRACK = 10,
  anon_sym_RBRACK = 11,
  anon_sym_LPAREN = 12,
  anon_sym_RPAREN = 13,
  anon_sym_type = 14,
  anon_sym_PLUS = 15,
  anon_sym_STAR = 16,
  anon_sym_DASH = 17,
  anon_sym_PERCENTmode = 18,
  anon_sym_PERCENTtotal = 19,
  anon_sym_PERCENTworlds = 20,
  anon_sym_PIPE = 21,
  sym_comment = 22,
  sym_id = 23,
  sym_source_file = 24,
  sym__declaration = 25,
  sym_decl = 26,
  sym_defn = 27,
  sym_solve_decl = 28,
  sym_tm_fun = 29,
  sym_tm_pi = 30,
  sym_tm_lam = 31,
  sym_tm_app = 32,
  sym_tm_ascrip = 33,
  sym_tm_bracket = 34,
  sym__term = 35,
  sym_mode = 36,
  sym_mid = 37,
  sym_mode_decl = 38,
  sym_callpat = 39,
  sym_order = 40,
  sym_total_decl = 41,
  sym_worlds_decl = 42,
  aux_sym_source_file_repeat1 = 43,
  aux_sym_mode_decl_repeat1 = 44,
  aux_sym_mode_decl_repeat2 = 45,
  aux_sym_mode_decl_repeat3 = 46,
  aux_sym_callpat_repeat1 = 47,
  aux_sym_order_repeat1 = 48,
  aux_sym_total_decl_repeat1 = 49,
  aux_sym_worlds_decl_repeat1 = 50,
  alias_sym_tm_hole = 51,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_DOT] = ".",
  [anon_sym__] = "anon",
  [anon_sym_COLON] = ":",
  [anon_sym_EQ] = "=",
  [anon_sym_PERCENTsolve] = "%solve",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_LT_DASH] = "<-",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_type] = "tm_type",
  [anon_sym_PLUS] = "+",
  [anon_sym_STAR] = "*",
  [anon_sym_DASH] = "-",
  [anon_sym_PERCENTmode] = "%mode",
  [anon_sym_PERCENTtotal] = "%total",
  [anon_sym_PERCENTworlds] = "%worlds",
  [anon_sym_PIPE] = "|",
  [sym_comment] = "comment",
  [sym_id] = "id",
  [sym_source_file] = "source_file",
  [sym__declaration] = "_declaration",
  [sym_decl] = "decl",
  [sym_defn] = "defn",
  [sym_solve_decl] = "solve_decl",
  [sym_tm_fun] = "tm_fun",
  [sym_tm_pi] = "tm_pi",
  [sym_tm_lam] = "tm_lam",
  [sym_tm_app] = "tm_app",
  [sym_tm_ascrip] = "tm_ascrip",
  [sym_tm_bracket] = "tm_bracket",
  [sym__term] = "_term",
  [sym_mode] = "mode",
  [sym_mid] = "mid",
  [sym_mode_decl] = "mode_decl",
  [sym_callpat] = "callpat",
  [sym_order] = "order",
  [sym_total_decl] = "total_decl",
  [sym_worlds_decl] = "worlds_decl",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_mode_decl_repeat1] = "mode_decl_repeat1",
  [aux_sym_mode_decl_repeat2] = "mode_decl_repeat2",
  [aux_sym_mode_decl_repeat3] = "mode_decl_repeat3",
  [aux_sym_callpat_repeat1] = "callpat_repeat1",
  [aux_sym_order_repeat1] = "order_repeat1",
  [aux_sym_total_decl_repeat1] = "total_decl_repeat1",
  [aux_sym_worlds_decl_repeat1] = "worlds_decl_repeat1",
  [alias_sym_tm_hole] = "tm_hole",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym__] = anon_sym__,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_PERCENTsolve] = anon_sym_PERCENTsolve,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_LT_DASH] = anon_sym_LT_DASH,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_PERCENTmode] = anon_sym_PERCENTmode,
  [anon_sym_PERCENTtotal] = anon_sym_PERCENTtotal,
  [anon_sym_PERCENTworlds] = anon_sym_PERCENTworlds,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [sym_comment] = sym_comment,
  [sym_id] = sym_id,
  [sym_source_file] = sym_source_file,
  [sym__declaration] = sym__declaration,
  [sym_decl] = sym_decl,
  [sym_defn] = sym_defn,
  [sym_solve_decl] = sym_solve_decl,
  [sym_tm_fun] = sym_tm_fun,
  [sym_tm_pi] = sym_tm_pi,
  [sym_tm_lam] = sym_tm_lam,
  [sym_tm_app] = sym_tm_app,
  [sym_tm_ascrip] = sym_tm_ascrip,
  [sym_tm_bracket] = sym_tm_bracket,
  [sym__term] = sym__term,
  [sym_mode] = sym_mode,
  [sym_mid] = sym_mid,
  [sym_mode_decl] = sym_mode_decl,
  [sym_callpat] = sym_callpat,
  [sym_order] = sym_order,
  [sym_total_decl] = sym_total_decl,
  [sym_worlds_decl] = sym_worlds_decl,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_mode_decl_repeat1] = aux_sym_mode_decl_repeat1,
  [aux_sym_mode_decl_repeat2] = aux_sym_mode_decl_repeat2,
  [aux_sym_mode_decl_repeat3] = aux_sym_mode_decl_repeat3,
  [aux_sym_callpat_repeat1] = aux_sym_callpat_repeat1,
  [aux_sym_order_repeat1] = aux_sym_order_repeat1,
  [aux_sym_total_decl_repeat1] = aux_sym_total_decl_repeat1,
  [aux_sym_worlds_decl_repeat1] = aux_sym_worlds_decl_repeat1,
  [alias_sym_tm_hole] = alias_sym_tm_hole,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENTsolve] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENTmode] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENTtotal] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENTworlds] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_id] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__declaration] = {
    .visible = false,
    .named = true,
  },
  [sym_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_defn] = {
    .visible = true,
    .named = true,
  },
  [sym_solve_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_tm_fun] = {
    .visible = true,
    .named = true,
  },
  [sym_tm_pi] = {
    .visible = true,
    .named = true,
  },
  [sym_tm_lam] = {
    .visible = true,
    .named = true,
  },
  [sym_tm_app] = {
    .visible = true,
    .named = true,
  },
  [sym_tm_ascrip] = {
    .visible = true,
    .named = true,
  },
  [sym_tm_bracket] = {
    .visible = true,
    .named = true,
  },
  [sym__term] = {
    .visible = false,
    .named = true,
  },
  [sym_mode] = {
    .visible = true,
    .named = true,
  },
  [sym_mid] = {
    .visible = true,
    .named = true,
  },
  [sym_mode_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_callpat] = {
    .visible = true,
    .named = true,
  },
  [sym_order] = {
    .visible = true,
    .named = true,
  },
  [sym_total_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_worlds_decl] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_mode_decl_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_mode_decl_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_mode_decl_repeat3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_callpat_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_order_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_total_decl_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_worlds_decl_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_tm_hole] = {
    .visible = true,
    .named = true,
  },
};

enum {
  field_from = 1,
  field_to = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_from] = "from",
  [field_to] = "to",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [2] = {.index = 0, .length = 2},
  [3] = {.index = 2, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_from, 0},
    {field_to, 2},
  [2] =
    {field_from, 2},
    {field_to, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = alias_sym_tm_hole,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 3,
  [11] = 5,
  [12] = 4,
  [13] = 9,
  [14] = 2,
  [15] = 6,
  [16] = 16,
  [17] = 8,
  [18] = 7,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 22,
  [26] = 24,
  [27] = 19,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 35,
  [44] = 37,
  [45] = 39,
  [46] = 46,
  [47] = 36,
  [48] = 33,
  [49] = 49,
  [50] = 50,
  [51] = 42,
  [52] = 41,
  [53] = 32,
  [54] = 54,
  [55] = 38,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 49,
  [60] = 46,
  [61] = 40,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 104,
  [110] = 110,
  [111] = 110,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 117,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 119,
  [124] = 124,
  [125] = 125,
  [126] = 126,
};

static inline bool sym_id_character_set_1(int32_t c) {
  return (c < ':'
    ? (c < '('
      ? (c < '"'
        ? c == 0
        : c <= '"')
      : (c <= '(' || c == '.'))
    : (c <= ':' || (c < '{'
      ? (c < ']'
        ? c == '['
        : c <= ']')
      : (c <= '{' || c == '}'))));
}

static inline bool sym_id_character_set_2(int32_t c) {
  return (c < '('
    ? (c < ' '
      ? (c < '\t'
        ? c == 0
        : (c <= '\n' || c == '\r'))
      : (c <= ' ' || (c < '%'
        ? c == '"'
        : c <= '%')))
    : (c <= ')' || (c < ']'
      ? (c < ':'
        ? c == '.'
        : (c <= ':' || c == '['))
      : (c <= ']' || (c < '}'
        ? c == '{'
        : c <= '}')))));
}

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(28);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (lookahead == '%') ADVANCE(1);
      if (lookahead == '(') ADVANCE(43);
      if (lookahead == ')') ADVANCE(44);
      if (lookahead == '*') ADVANCE(48);
      if (lookahead == '+') ADVANCE(47);
      if (lookahead == '-') ADVANCE(49);
      if (lookahead == '.') ADVANCE(29);
      if (lookahead == ':') ADVANCE(32);
      if (lookahead == '<') ADVANCE(3);
      if (lookahead == '=') ADVANCE(33);
      if (lookahead == '[') ADVANCE(41);
      if (lookahead == ']') ADVANCE(42);
      if (lookahead == '_') ADVANCE(30);
      if (lookahead == 't') ADVANCE(22);
      if (lookahead == '{') ADVANCE(39);
      if (lookahead == '|') ADVANCE(53);
      if (lookahead == '}') ADVANCE(40);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(54);
      if (lookahead == 'm') ADVANCE(13);
      if (lookahead == 's') ADVANCE(14);
      if (lookahead == 't') ADVANCE(15);
      if (lookahead == 'w') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == ' ' ||
          lookahead == '%') ADVANCE(55);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(54);
      if (lookahead == '\t' ||
          lookahead == ' ' ||
          lookahead == '%') ADVANCE(55);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(37);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(11);
      END_STATE();
    case 5:
      if (lookahead == 'd') ADVANCE(19);
      END_STATE();
    case 6:
      if (lookahead == 'd') ADVANCE(8);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(45);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(50);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(35);
      END_STATE();
    case 10:
      if (lookahead == 'l') ADVANCE(21);
      END_STATE();
    case 11:
      if (lookahead == 'l') ADVANCE(51);
      END_STATE();
    case 12:
      if (lookahead == 'l') ADVANCE(5);
      END_STATE();
    case 13:
      if (lookahead == 'o') ADVANCE(6);
      END_STATE();
    case 14:
      if (lookahead == 'o') ADVANCE(10);
      END_STATE();
    case 15:
      if (lookahead == 'o') ADVANCE(20);
      END_STATE();
    case 16:
      if (lookahead == 'o') ADVANCE(18);
      END_STATE();
    case 17:
      if (lookahead == 'p') ADVANCE(7);
      END_STATE();
    case 18:
      if (lookahead == 'r') ADVANCE(12);
      END_STATE();
    case 19:
      if (lookahead == 's') ADVANCE(52);
      END_STATE();
    case 20:
      if (lookahead == 't') ADVANCE(4);
      END_STATE();
    case 21:
      if (lookahead == 'v') ADVANCE(9);
      END_STATE();
    case 22:
      if (lookahead == 'y') ADVANCE(17);
      END_STATE();
    case 23:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(23)
      if (lookahead == '%') ADVANCE(2);
      if (lookahead == '(') ADVANCE(43);
      if (lookahead == ')') ADVANCE(44);
      if (lookahead == '-') ADVANCE(57);
      if (lookahead == '.') ADVANCE(29);
      if (lookahead == ':') ADVANCE(32);
      if (lookahead == '<') ADVANCE(56);
      if (lookahead == '[') ADVANCE(41);
      if (lookahead == ']') ADVANCE(42);
      if (lookahead == '_') ADVANCE(31);
      if (lookahead == 't') ADVANCE(60);
      if (lookahead == '{') ADVANCE(39);
      if (lookahead == '}') ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(61);
      END_STATE();
    case 24:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(24)
      if (lookahead == '%') ADVANCE(2);
      if (lookahead == '(') ADVANCE(43);
      if (lookahead == '-') ADVANCE(57);
      if (lookahead == '.') ADVANCE(29);
      if (lookahead == ':') ADVANCE(32);
      if (lookahead == '<') ADVANCE(56);
      if (lookahead == '=') ADVANCE(34);
      if (lookahead == '[') ADVANCE(41);
      if (lookahead == '_') ADVANCE(31);
      if (lookahead == 't') ADVANCE(60);
      if (lookahead == '{') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != ')' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(61);
      END_STATE();
    case 25:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(25)
      if (lookahead == '%') ADVANCE(2);
      if (lookahead == '(') ADVANCE(43);
      if (lookahead == '[') ADVANCE(41);
      if (lookahead == '_') ADVANCE(31);
      if (lookahead == 't') ADVANCE(60);
      if (lookahead == '{') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != ')' &&
          lookahead != '.' &&
          lookahead != ':' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(61);
      END_STATE();
    case 26:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(26)
      if (lookahead == '%') ADVANCE(2);
      if (lookahead == '(') ADVANCE(43);
      if (lookahead == ')') ADVANCE(44);
      if (lookahead == '.') ADVANCE(29);
      if (lookahead == '[') ADVANCE(41);
      if (lookahead == ']') ADVANCE(42);
      if (lookahead == '{') ADVANCE(39);
      if (lookahead == '}') ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != ':') ADVANCE(61);
      END_STATE();
    case 27:
      if (eof) ADVANCE(28);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(27)
      if (lookahead == '%') ADVANCE(1);
      if (lookahead == ')') ADVANCE(44);
      if (lookahead == '_') ADVANCE(31);
      if (!sym_id_character_set_1(lookahead)) ADVANCE(61);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym__);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym__);
      if (!sym_id_character_set_2(lookahead)) ADVANCE(61);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (!sym_id_character_set_2(lookahead)) ADVANCE(61);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_PERCENTsolve);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      if (!sym_id_character_set_2(lookahead)) ADVANCE(61);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LT_DASH);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_LT_DASH);
      if (!sym_id_character_set_2(lookahead)) ADVANCE(61);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_type);
      if (!sym_id_character_set_2(lookahead)) ADVANCE(61);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_PERCENTmode);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_PERCENTtotal);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_PERCENTworlds);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_id);
      if (lookahead == '-') ADVANCE(38);
      if (!sym_id_character_set_2(lookahead)) ADVANCE(61);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_id);
      if (lookahead == '>') ADVANCE(36);
      if (!sym_id_character_set_2(lookahead)) ADVANCE(61);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_id);
      if (lookahead == 'e') ADVANCE(46);
      if (!sym_id_character_set_2(lookahead)) ADVANCE(61);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_id);
      if (lookahead == 'p') ADVANCE(58);
      if (!sym_id_character_set_2(lookahead)) ADVANCE(61);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_id);
      if (lookahead == 'y') ADVANCE(59);
      if (!sym_id_character_set_2(lookahead)) ADVANCE(61);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_id);
      if (!sym_id_character_set_2(lookahead)) ADVANCE(61);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 27},
  [2] = {.lex_state = 23},
  [3] = {.lex_state = 23},
  [4] = {.lex_state = 23},
  [5] = {.lex_state = 23},
  [6] = {.lex_state = 23},
  [7] = {.lex_state = 23},
  [8] = {.lex_state = 23},
  [9] = {.lex_state = 23},
  [10] = {.lex_state = 24},
  [11] = {.lex_state = 24},
  [12] = {.lex_state = 24},
  [13] = {.lex_state = 24},
  [14] = {.lex_state = 24},
  [15] = {.lex_state = 24},
  [16] = {.lex_state = 24},
  [17] = {.lex_state = 24},
  [18] = {.lex_state = 24},
  [19] = {.lex_state = 23},
  [20] = {.lex_state = 23},
  [21] = {.lex_state = 23},
  [22] = {.lex_state = 23},
  [23] = {.lex_state = 23},
  [24] = {.lex_state = 23},
  [25] = {.lex_state = 23},
  [26] = {.lex_state = 23},
  [27] = {.lex_state = 23},
  [28] = {.lex_state = 23},
  [29] = {.lex_state = 23},
  [30] = {.lex_state = 27},
  [31] = {.lex_state = 27},
  [32] = {.lex_state = 25},
  [33] = {.lex_state = 25},
  [34] = {.lex_state = 25},
  [35] = {.lex_state = 25},
  [36] = {.lex_state = 25},
  [37] = {.lex_state = 25},
  [38] = {.lex_state = 25},
  [39] = {.lex_state = 25},
  [40] = {.lex_state = 23},
  [41] = {.lex_state = 25},
  [42] = {.lex_state = 25},
  [43] = {.lex_state = 25},
  [44] = {.lex_state = 25},
  [45] = {.lex_state = 25},
  [46] = {.lex_state = 23},
  [47] = {.lex_state = 25},
  [48] = {.lex_state = 25},
  [49] = {.lex_state = 25},
  [50] = {.lex_state = 25},
  [51] = {.lex_state = 25},
  [52] = {.lex_state = 25},
  [53] = {.lex_state = 25},
  [54] = {.lex_state = 25},
  [55] = {.lex_state = 25},
  [56] = {.lex_state = 25},
  [57] = {.lex_state = 25},
  [58] = {.lex_state = 25},
  [59] = {.lex_state = 25},
  [60] = {.lex_state = 24},
  [61] = {.lex_state = 24},
  [62] = {.lex_state = 26},
  [63] = {.lex_state = 26},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 26},
  [67] = {.lex_state = 26},
  [68] = {.lex_state = 26},
  [69] = {.lex_state = 27},
  [70] = {.lex_state = 26},
  [71] = {.lex_state = 26},
  [72] = {.lex_state = 26},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 26},
  [75] = {.lex_state = 26},
  [76] = {.lex_state = 27},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 27},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 27},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 26},
  [85] = {.lex_state = 26},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 26},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 26},
  [92] = {.lex_state = 26},
  [93] = {.lex_state = 26},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 26},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 26},
  [102] = {.lex_state = 26},
  [103] = {.lex_state = 27},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 26},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 26},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 26},
  [114] = {.lex_state = 26},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 26},
  [118] = {.lex_state = 26},
  [119] = {.lex_state = 26},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 26},
  [123] = {.lex_state = 26},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 26},
  [126] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_PERCENTsolve] = ACTIONS(1),
    [anon_sym_LT_DASH] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_PERCENTmode] = ACTIONS(1),
    [anon_sym_PERCENTtotal] = ACTIONS(1),
    [anon_sym_PERCENTworlds] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(120),
    [sym__declaration] = STATE(30),
    [sym_decl] = STATE(126),
    [sym_defn] = STATE(126),
    [sym_solve_decl] = STATE(126),
    [sym_mode_decl] = STATE(126),
    [sym_total_decl] = STATE(126),
    [sym_worlds_decl] = STATE(126),
    [aux_sym_source_file_repeat1] = STATE(30),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym__] = ACTIONS(7),
    [anon_sym_PERCENTsolve] = ACTIONS(9),
    [anon_sym_PERCENTmode] = ACTIONS(11),
    [anon_sym_PERCENTtotal] = ACTIONS(13),
    [anon_sym_PERCENTworlds] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
    [sym_id] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym__,
    ACTIONS(23), 1,
      anon_sym_COLON,
    ACTIONS(25), 1,
      anon_sym_DASH_GT,
    ACTIONS(27), 1,
      anon_sym_LT_DASH,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 2,
      anon_sym_type,
      sym_id,
    ACTIONS(19), 4,
      anon_sym_DOT,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
    STATE(9), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [44] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 2,
      anon_sym_type,
      sym_id,
    ACTIONS(39), 2,
      anon_sym_DASH_GT,
      anon_sym_LT_DASH,
    ACTIONS(37), 5,
      anon_sym_DOT,
      anon_sym_COLON,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
    STATE(9), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [84] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym__,
    ACTIONS(23), 1,
      anon_sym_COLON,
    ACTIONS(25), 1,
      anon_sym_DASH_GT,
    ACTIONS(27), 1,
      anon_sym_LT_DASH,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 2,
      anon_sym_type,
      sym_id,
    ACTIONS(41), 4,
      anon_sym_DOT,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
    STATE(9), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [128] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 2,
      anon_sym_type,
      sym_id,
    ACTIONS(45), 2,
      anon_sym_DASH_GT,
      anon_sym_LT_DASH,
    ACTIONS(43), 5,
      anon_sym_DOT,
      anon_sym_COLON,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
    STATE(9), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [168] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym__,
    ACTIONS(23), 1,
      anon_sym_COLON,
    ACTIONS(25), 1,
      anon_sym_DASH_GT,
    ACTIONS(27), 1,
      anon_sym_LT_DASH,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 2,
      anon_sym_type,
      sym_id,
    ACTIONS(47), 4,
      anon_sym_DOT,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
    STATE(9), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [212] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym__,
    ACTIONS(23), 1,
      anon_sym_COLON,
    ACTIONS(25), 1,
      anon_sym_DASH_GT,
    ACTIONS(27), 1,
      anon_sym_LT_DASH,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 2,
      anon_sym_type,
      sym_id,
    ACTIONS(49), 4,
      anon_sym_DOT,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
    STATE(9), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [256] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym__,
    ACTIONS(23), 1,
      anon_sym_COLON,
    ACTIONS(25), 1,
      anon_sym_DASH_GT,
    ACTIONS(27), 1,
      anon_sym_LT_DASH,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 2,
      anon_sym_type,
      sym_id,
    ACTIONS(51), 4,
      anon_sym_DOT,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
    STATE(9), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [300] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 5,
      anon_sym__,
      anon_sym_DASH_GT,
      anon_sym_LT_DASH,
      anon_sym_type,
      sym_id,
    STATE(9), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
    ACTIONS(53), 8,
      anon_sym_DOT,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [330] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym__,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      anon_sym_LBRACK,
    ACTIONS(63), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 2,
      anon_sym_DOT,
      anon_sym_COLON,
    ACTIONS(65), 2,
      anon_sym_type,
      sym_id,
    ACTIONS(39), 3,
      anon_sym_EQ,
      anon_sym_DASH_GT,
      anon_sym_LT_DASH,
    STATE(13), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [368] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym__,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      anon_sym_LBRACK,
    ACTIONS(63), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 2,
      anon_sym_DOT,
      anon_sym_COLON,
    ACTIONS(65), 2,
      anon_sym_type,
      sym_id,
    ACTIONS(45), 3,
      anon_sym_EQ,
      anon_sym_DASH_GT,
      anon_sym_LT_DASH,
    STATE(13), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [406] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_DOT,
    ACTIONS(57), 1,
      anon_sym__,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      anon_sym_LBRACK,
    ACTIONS(63), 1,
      anon_sym_LPAREN,
    ACTIONS(67), 1,
      anon_sym_COLON,
    ACTIONS(69), 1,
      anon_sym_EQ,
    ACTIONS(71), 1,
      anon_sym_DASH_GT,
    ACTIONS(73), 1,
      anon_sym_LT_DASH,
    ACTIONS(65), 2,
      anon_sym_type,
      sym_id,
    STATE(13), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [450] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 5,
      anon_sym_DOT,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
    ACTIONS(55), 6,
      anon_sym__,
      anon_sym_EQ,
      anon_sym_DASH_GT,
      anon_sym_LT_DASH,
      anon_sym_type,
      sym_id,
    STATE(13), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [478] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_DOT,
    ACTIONS(57), 1,
      anon_sym__,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      anon_sym_LBRACK,
    ACTIONS(63), 1,
      anon_sym_LPAREN,
    ACTIONS(67), 1,
      anon_sym_COLON,
    ACTIONS(71), 1,
      anon_sym_DASH_GT,
    ACTIONS(73), 1,
      anon_sym_LT_DASH,
    ACTIONS(75), 1,
      anon_sym_EQ,
    ACTIONS(65), 2,
      anon_sym_type,
      sym_id,
    STATE(13), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [522] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(47), 1,
      anon_sym_DOT,
    ACTIONS(57), 1,
      anon_sym__,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      anon_sym_LBRACK,
    ACTIONS(63), 1,
      anon_sym_LPAREN,
    ACTIONS(67), 1,
      anon_sym_COLON,
    ACTIONS(71), 1,
      anon_sym_DASH_GT,
    ACTIONS(73), 1,
      anon_sym_LT_DASH,
    ACTIONS(77), 1,
      anon_sym_EQ,
    ACTIONS(65), 2,
      anon_sym_type,
      sym_id,
    STATE(13), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [566] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym__,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      anon_sym_LBRACK,
    ACTIONS(63), 1,
      anon_sym_LPAREN,
    ACTIONS(67), 1,
      anon_sym_COLON,
    ACTIONS(71), 1,
      anon_sym_DASH_GT,
    ACTIONS(73), 1,
      anon_sym_LT_DASH,
    ACTIONS(79), 1,
      anon_sym_DOT,
    ACTIONS(81), 1,
      anon_sym_EQ,
    ACTIONS(65), 2,
      anon_sym_type,
      sym_id,
    STATE(13), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [610] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 1,
      anon_sym_DOT,
    ACTIONS(57), 1,
      anon_sym__,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      anon_sym_LBRACK,
    ACTIONS(63), 1,
      anon_sym_LPAREN,
    ACTIONS(67), 1,
      anon_sym_COLON,
    ACTIONS(71), 1,
      anon_sym_DASH_GT,
    ACTIONS(73), 1,
      anon_sym_LT_DASH,
    ACTIONS(83), 1,
      anon_sym_EQ,
    ACTIONS(65), 2,
      anon_sym_type,
      sym_id,
    STATE(13), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [654] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 1,
      anon_sym_DOT,
    ACTIONS(57), 1,
      anon_sym__,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      anon_sym_LBRACK,
    ACTIONS(63), 1,
      anon_sym_LPAREN,
    ACTIONS(67), 1,
      anon_sym_COLON,
    ACTIONS(71), 1,
      anon_sym_DASH_GT,
    ACTIONS(73), 1,
      anon_sym_LT_DASH,
    ACTIONS(85), 1,
      anon_sym_EQ,
    ACTIONS(65), 2,
      anon_sym_type,
      sym_id,
    STATE(13), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [698] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym__,
    ACTIONS(23), 1,
      anon_sym_COLON,
    ACTIONS(25), 1,
      anon_sym_DASH_GT,
    ACTIONS(27), 1,
      anon_sym_LT_DASH,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(87), 1,
      anon_sym_RBRACE,
    ACTIONS(35), 2,
      anon_sym_type,
      sym_id,
    STATE(9), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [739] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym__,
    ACTIONS(23), 1,
      anon_sym_COLON,
    ACTIONS(25), 1,
      anon_sym_DASH_GT,
    ACTIONS(27), 1,
      anon_sym_LT_DASH,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(89), 1,
      anon_sym_RBRACE,
    ACTIONS(35), 2,
      anon_sym_type,
      sym_id,
    STATE(9), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [780] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym__,
    ACTIONS(23), 1,
      anon_sym_COLON,
    ACTIONS(25), 1,
      anon_sym_DASH_GT,
    ACTIONS(27), 1,
      anon_sym_LT_DASH,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(91), 1,
      anon_sym_DOT,
    ACTIONS(35), 2,
      anon_sym_type,
      sym_id,
    STATE(9), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [821] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym__,
    ACTIONS(23), 1,
      anon_sym_COLON,
    ACTIONS(25), 1,
      anon_sym_DASH_GT,
    ACTIONS(27), 1,
      anon_sym_LT_DASH,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(93), 1,
      anon_sym_RPAREN,
    ACTIONS(35), 2,
      anon_sym_type,
      sym_id,
    STATE(9), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [862] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym__,
    ACTIONS(23), 1,
      anon_sym_COLON,
    ACTIONS(25), 1,
      anon_sym_DASH_GT,
    ACTIONS(27), 1,
      anon_sym_LT_DASH,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(95), 1,
      anon_sym_DOT,
    ACTIONS(35), 2,
      anon_sym_type,
      sym_id,
    STATE(9), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [903] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym__,
    ACTIONS(23), 1,
      anon_sym_COLON,
    ACTIONS(25), 1,
      anon_sym_DASH_GT,
    ACTIONS(27), 1,
      anon_sym_LT_DASH,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(97), 1,
      anon_sym_RBRACK,
    ACTIONS(35), 2,
      anon_sym_type,
      sym_id,
    STATE(9), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [944] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym__,
    ACTIONS(23), 1,
      anon_sym_COLON,
    ACTIONS(25), 1,
      anon_sym_DASH_GT,
    ACTIONS(27), 1,
      anon_sym_LT_DASH,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(99), 1,
      anon_sym_RPAREN,
    ACTIONS(35), 2,
      anon_sym_type,
      sym_id,
    STATE(9), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [985] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym__,
    ACTIONS(23), 1,
      anon_sym_COLON,
    ACTIONS(25), 1,
      anon_sym_DASH_GT,
    ACTIONS(27), 1,
      anon_sym_LT_DASH,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(101), 1,
      anon_sym_RBRACK,
    ACTIONS(35), 2,
      anon_sym_type,
      sym_id,
    STATE(9), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1026] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym__,
    ACTIONS(23), 1,
      anon_sym_COLON,
    ACTIONS(25), 1,
      anon_sym_DASH_GT,
    ACTIONS(27), 1,
      anon_sym_LT_DASH,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(103), 1,
      anon_sym_RBRACE,
    ACTIONS(35), 2,
      anon_sym_type,
      sym_id,
    STATE(9), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1067] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym__,
    ACTIONS(23), 1,
      anon_sym_COLON,
    ACTIONS(25), 1,
      anon_sym_DASH_GT,
    ACTIONS(27), 1,
      anon_sym_LT_DASH,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(79), 1,
      anon_sym_DOT,
    ACTIONS(35), 2,
      anon_sym_type,
      sym_id,
    STATE(9), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1108] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym__,
    ACTIONS(23), 1,
      anon_sym_COLON,
    ACTIONS(25), 1,
      anon_sym_DASH_GT,
    ACTIONS(27), 1,
      anon_sym_LT_DASH,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(105), 1,
      anon_sym_DOT,
    ACTIONS(35), 2,
      anon_sym_type,
      sym_id,
    STATE(9), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1149] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym__,
    ACTIONS(9), 1,
      anon_sym_PERCENTsolve,
    ACTIONS(11), 1,
      anon_sym_PERCENTmode,
    ACTIONS(13), 1,
      anon_sym_PERCENTtotal,
    ACTIONS(15), 1,
      anon_sym_PERCENTworlds,
    ACTIONS(17), 1,
      sym_id,
    ACTIONS(107), 1,
      ts_builtin_sym_end,
    STATE(31), 2,
      sym__declaration,
      aux_sym_source_file_repeat1,
    STATE(126), 6,
      sym_decl,
      sym_defn,
      sym_solve_decl,
      sym_mode_decl,
      sym_total_decl,
      sym_worlds_decl,
  [1186] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 1,
      ts_builtin_sym_end,
    ACTIONS(111), 1,
      anon_sym__,
    ACTIONS(114), 1,
      anon_sym_PERCENTsolve,
    ACTIONS(117), 1,
      anon_sym_PERCENTmode,
    ACTIONS(120), 1,
      anon_sym_PERCENTtotal,
    ACTIONS(123), 1,
      anon_sym_PERCENTworlds,
    ACTIONS(126), 1,
      sym_id,
    STATE(31), 2,
      sym__declaration,
      aux_sym_source_file_repeat1,
    STATE(126), 6,
      sym_decl,
      sym_defn,
      sym_solve_decl,
      sym_mode_decl,
      sym_total_decl,
      sym_worlds_decl,
  [1223] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym__,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      anon_sym_LBRACK,
    ACTIONS(63), 1,
      anon_sym_LPAREN,
    ACTIONS(129), 2,
      anon_sym_type,
      sym_id,
    STATE(10), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1252] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym__,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      anon_sym_LBRACK,
    ACTIONS(63), 1,
      anon_sym_LPAREN,
    ACTIONS(131), 2,
      anon_sym_type,
      sym_id,
    STATE(14), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1281] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(133), 2,
      anon_sym_type,
      sym_id,
    STATE(20), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1310] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym__,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      anon_sym_LBRACK,
    ACTIONS(63), 1,
      anon_sym_LPAREN,
    ACTIONS(135), 2,
      anon_sym_type,
      sym_id,
    STATE(17), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1339] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym__,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      anon_sym_LBRACK,
    ACTIONS(63), 1,
      anon_sym_LPAREN,
    ACTIONS(137), 2,
      anon_sym_type,
      sym_id,
    STATE(18), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1368] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(139), 2,
      anon_sym_type,
      sym_id,
    STATE(26), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1397] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(141), 2,
      anon_sym_type,
      sym_id,
    STATE(19), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1426] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(143), 2,
      anon_sym_type,
      sym_id,
    STATE(25), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1455] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 5,
      anon_sym__,
      anon_sym_DASH_GT,
      anon_sym_LT_DASH,
      anon_sym_type,
      sym_id,
    ACTIONS(145), 8,
      anon_sym_DOT,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [1476] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym__,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      anon_sym_LBRACK,
    ACTIONS(63), 1,
      anon_sym_LPAREN,
    ACTIONS(149), 2,
      anon_sym_type,
      sym_id,
    STATE(12), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1505] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym__,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      anon_sym_LBRACK,
    ACTIONS(63), 1,
      anon_sym_LPAREN,
    ACTIONS(151), 2,
      anon_sym_type,
      sym_id,
    STATE(11), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1534] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 2,
      anon_sym_type,
      sym_id,
    STATE(8), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1563] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(155), 2,
      anon_sym_type,
      sym_id,
    STATE(24), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1592] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(157), 2,
      anon_sym_type,
      sym_id,
    STATE(22), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1621] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 5,
      anon_sym__,
      anon_sym_DASH_GT,
      anon_sym_LT_DASH,
      anon_sym_type,
      sym_id,
    ACTIONS(159), 8,
      anon_sym_DOT,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [1642] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(163), 2,
      anon_sym_type,
      sym_id,
    STATE(7), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1671] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(165), 2,
      anon_sym_type,
      sym_id,
    STATE(2), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1700] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(167), 2,
      anon_sym_type,
      sym_id,
    STATE(6), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1729] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(169), 2,
      anon_sym_type,
      sym_id,
    STATE(23), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1758] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(171), 2,
      anon_sym_type,
      sym_id,
    STATE(5), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1787] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(173), 2,
      anon_sym_type,
      sym_id,
    STATE(4), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1816] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(175), 2,
      anon_sym_type,
      sym_id,
    STATE(3), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1845] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym__,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      anon_sym_LBRACK,
    ACTIONS(63), 1,
      anon_sym_LPAREN,
    ACTIONS(177), 2,
      anon_sym_type,
      sym_id,
    STATE(16), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1874] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(179), 2,
      anon_sym_type,
      sym_id,
    STATE(27), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1903] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(181), 2,
      anon_sym_type,
      sym_id,
    STATE(29), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1932] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(183), 2,
      anon_sym_type,
      sym_id,
    STATE(28), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1961] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym__,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(185), 2,
      anon_sym_type,
      sym_id,
    STATE(21), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [1990] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym__,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      anon_sym_LBRACK,
    ACTIONS(63), 1,
      anon_sym_LPAREN,
    ACTIONS(187), 2,
      anon_sym_type,
      sym_id,
    STATE(15), 7,
      sym_tm_fun,
      sym_tm_pi,
      sym_tm_lam,
      sym_tm_app,
      sym_tm_ascrip,
      sym_tm_bracket,
      sym__term,
  [2019] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 5,
      anon_sym_DOT,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
    ACTIONS(161), 6,
      anon_sym__,
      anon_sym_EQ,
      anon_sym_DASH_GT,
      anon_sym_LT_DASH,
      anon_sym_type,
      sym_id,
  [2038] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 5,
      anon_sym_DOT,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
    ACTIONS(147), 6,
      anon_sym__,
      anon_sym_EQ,
      anon_sym_DASH_GT,
      anon_sym_LT_DASH,
      anon_sym_type,
      sym_id,
  [2057] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 1,
      anon_sym_LBRACE,
    ACTIONS(194), 1,
      anon_sym_LBRACK,
    ACTIONS(197), 1,
      anon_sym_LPAREN,
    ACTIONS(200), 1,
      sym_id,
    ACTIONS(192), 2,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
    STATE(62), 2,
      sym_order,
      aux_sym_order_repeat1,
  [2081] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 7,
      anon_sym_DOT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      sym_id,
  [2094] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      anon_sym_DOT,
    STATE(113), 1,
      sym_mode,
    STATE(73), 2,
      sym_mid,
      aux_sym_mode_decl_repeat1,
    ACTIONS(207), 3,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_DASH,
  [2113] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 1,
      anon_sym_DOT,
    STATE(113), 1,
      sym_mode,
    STATE(65), 2,
      sym_mid,
      aux_sym_mode_decl_repeat1,
    ACTIONS(211), 3,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_DASH,
  [2132] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 1,
      anon_sym_LBRACE,
    ACTIONS(216), 1,
      anon_sym_RBRACE,
    ACTIONS(218), 1,
      anon_sym_LBRACK,
    ACTIONS(220), 1,
      anon_sym_LPAREN,
    ACTIONS(222), 1,
      sym_id,
    STATE(71), 2,
      sym_order,
      aux_sym_order_repeat1,
  [2155] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 1,
      anon_sym_LBRACE,
    ACTIONS(216), 1,
      anon_sym_RBRACK,
    ACTIONS(218), 1,
      anon_sym_LBRACK,
    ACTIONS(220), 1,
      anon_sym_LPAREN,
    ACTIONS(222), 1,
      sym_id,
    STATE(70), 2,
      sym_order,
      aux_sym_order_repeat1,
  [2178] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 7,
      anon_sym_DOT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      sym_id,
  [2191] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 2,
      anon_sym__,
      sym_id,
    ACTIONS(226), 5,
      ts_builtin_sym_end,
      anon_sym_PERCENTsolve,
      anon_sym_PERCENTmode,
      anon_sym_PERCENTtotal,
      anon_sym_PERCENTworlds,
  [2206] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 1,
      anon_sym_LBRACE,
    ACTIONS(218), 1,
      anon_sym_LBRACK,
    ACTIONS(220), 1,
      anon_sym_LPAREN,
    ACTIONS(222), 1,
      sym_id,
    ACTIONS(230), 1,
      anon_sym_RBRACK,
    STATE(62), 2,
      sym_order,
      aux_sym_order_repeat1,
  [2229] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 1,
      anon_sym_LBRACE,
    ACTIONS(218), 1,
      anon_sym_LBRACK,
    ACTIONS(220), 1,
      anon_sym_LPAREN,
    ACTIONS(222), 1,
      sym_id,
    ACTIONS(230), 1,
      anon_sym_RBRACE,
    STATE(62), 2,
      sym_order,
      aux_sym_order_repeat1,
  [2252] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 7,
      anon_sym_DOT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      sym_id,
  [2265] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      anon_sym_DOT,
    STATE(113), 1,
      sym_mode,
    STATE(65), 2,
      sym_mid,
      aux_sym_mode_decl_repeat1,
    ACTIONS(207), 3,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_DASH,
  [2284] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 1,
      anon_sym_LBRACE,
    ACTIONS(218), 1,
      anon_sym_LBRACK,
    ACTIONS(220), 1,
      anon_sym_LPAREN,
    ACTIONS(222), 1,
      sym_id,
    STATE(95), 1,
      sym_order,
  [2303] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 1,
      sym_id,
    STATE(75), 1,
      aux_sym_mode_decl_repeat3,
    ACTIONS(236), 2,
      anon_sym_DOT,
      anon_sym_RPAREN,
  [2317] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      anon_sym_RPAREN,
    STATE(78), 1,
      aux_sym_callpat_repeat1,
    ACTIONS(241), 2,
      anon_sym__,
      sym_id,
  [2331] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(125), 1,
      sym_mode,
    ACTIONS(207), 3,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_DASH,
  [2343] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 1,
      anon_sym_RPAREN,
    STATE(78), 1,
      aux_sym_callpat_repeat1,
    ACTIONS(245), 2,
      anon_sym__,
      sym_id,
  [2357] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 4,
      anon_sym_DOT,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_DASH,
  [2367] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      anon_sym_RPAREN,
    STATE(76), 1,
      aux_sym_callpat_repeat1,
    ACTIONS(252), 2,
      anon_sym__,
      sym_id,
  [2381] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 1,
      anon_sym_DOT,
    ACTIONS(258), 1,
      anon_sym_LPAREN,
    STATE(98), 1,
      aux_sym_total_decl_repeat1,
  [2394] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      anon_sym_LPAREN,
    ACTIONS(260), 1,
      anon_sym_DOT,
    STATE(86), 1,
      aux_sym_total_decl_repeat1,
  [2407] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(262), 1,
      anon_sym_RPAREN,
    ACTIONS(264), 1,
      anon_sym_PIPE,
    STATE(89), 1,
      aux_sym_worlds_decl_repeat1,
  [2420] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      anon_sym_DOT,
    ACTIONS(266), 1,
      sym_id,
    STATE(93), 1,
      aux_sym_mode_decl_repeat3,
  [2433] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 1,
      anon_sym_RPAREN,
    ACTIONS(268), 1,
      sym_id,
    STATE(75), 1,
      aux_sym_mode_decl_repeat3,
  [2446] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      anon_sym_LPAREN,
    ACTIONS(270), 1,
      anon_sym_DOT,
    STATE(90), 1,
      aux_sym_total_decl_repeat1,
  [2459] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(272), 1,
      anon_sym_LBRACE,
    ACTIONS(274), 1,
      sym_id,
    STATE(96), 1,
      aux_sym_mode_decl_repeat2,
  [2472] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      anon_sym_LPAREN,
    ACTIONS(270), 1,
      anon_sym_DOT,
    STATE(94), 1,
      aux_sym_total_decl_repeat1,
  [2485] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(276), 1,
      anon_sym_RPAREN,
    ACTIONS(278), 1,
      anon_sym_PIPE,
    STATE(89), 1,
      aux_sym_worlds_decl_repeat1,
  [2498] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 1,
      anon_sym_DOT,
    ACTIONS(283), 1,
      anon_sym_LPAREN,
    STATE(90), 1,
      aux_sym_total_decl_repeat1,
  [2511] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(272), 1,
      anon_sym_LBRACE,
    ACTIONS(286), 1,
      sym_id,
    STATE(87), 1,
      aux_sym_mode_decl_repeat2,
  [2524] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 1,
      anon_sym_RPAREN,
    ACTIONS(288), 1,
      sym_id,
    STATE(85), 1,
      aux_sym_mode_decl_repeat3,
  [2537] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      sym_id,
    ACTIONS(290), 1,
      anon_sym_DOT,
    STATE(75), 1,
      aux_sym_mode_decl_repeat3,
  [2550] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      anon_sym_LPAREN,
    ACTIONS(292), 1,
      anon_sym_DOT,
    STATE(90), 1,
      aux_sym_total_decl_repeat1,
  [2563] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      anon_sym_LPAREN,
    ACTIONS(294), 1,
      anon_sym_DOT,
    STATE(97), 1,
      aux_sym_total_decl_repeat1,
  [2576] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(296), 1,
      anon_sym_LBRACE,
    ACTIONS(299), 1,
      sym_id,
    STATE(96), 1,
      aux_sym_mode_decl_repeat2,
  [2589] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      anon_sym_LPAREN,
    ACTIONS(301), 1,
      anon_sym_DOT,
    STATE(90), 1,
      aux_sym_total_decl_repeat1,
  [2602] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      anon_sym_LPAREN,
    ACTIONS(260), 1,
      anon_sym_DOT,
    STATE(90), 1,
      aux_sym_total_decl_repeat1,
  [2615] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(264), 1,
      anon_sym_PIPE,
    ACTIONS(303), 1,
      anon_sym_RPAREN,
    STATE(83), 1,
      aux_sym_worlds_decl_repeat1,
  [2628] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(276), 2,
      anon_sym_RPAREN,
      anon_sym_PIPE,
  [2636] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(305), 2,
      anon_sym_LBRACE,
      sym_id,
  [2644] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(307), 1,
      sym_id,
    STATE(115), 1,
      sym_callpat,
  [2654] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(309), 2,
      anon_sym__,
      sym_id,
  [2662] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(311), 1,
      anon_sym_COLON,
    ACTIONS(313), 1,
      anon_sym_RBRACK,
  [2672] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(315), 1,
      anon_sym_COLON,
    ACTIONS(317), 1,
      anon_sym_EQ,
  [2682] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(319), 1,
      anon_sym_RPAREN,
    ACTIONS(321), 1,
      sym_id,
  [2692] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(323), 1,
      anon_sym_COLON,
    ACTIONS(325), 1,
      anon_sym_RBRACE,
  [2702] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(327), 2,
      anon_sym_LBRACE,
      sym_id,
  [2710] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(329), 1,
      anon_sym_COLON,
    ACTIONS(331), 1,
      anon_sym_RBRACK,
  [2720] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(333), 1,
      anon_sym_COLON,
    ACTIONS(335), 1,
      anon_sym_RBRACE,
  [2730] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(337), 1,
      anon_sym_COLON,
    ACTIONS(339), 1,
      anon_sym_RBRACE,
  [2740] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(341), 2,
      anon_sym_DOT,
      anon_sym_LPAREN,
  [2748] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(343), 1,
      sym_id,
  [2755] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(345), 1,
      sym_id,
  [2762] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(347), 1,
      anon_sym_RPAREN,
  [2769] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(349), 1,
      anon_sym_COLON,
  [2776] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(351), 1,
      sym_id,
  [2783] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(353), 1,
      sym_id,
  [2790] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(355), 1,
      sym_id,
  [2797] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(357), 1,
      ts_builtin_sym_end,
  [2804] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(359), 1,
      anon_sym_LPAREN,
  [2811] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(361), 1,
      sym_id,
  [2818] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(363), 1,
      sym_id,
  [2825] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(365), 1,
      anon_sym_COLON,
  [2832] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(367), 1,
      sym_id,
  [2839] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(369), 1,
      anon_sym_DOT,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 44,
  [SMALL_STATE(4)] = 84,
  [SMALL_STATE(5)] = 128,
  [SMALL_STATE(6)] = 168,
  [SMALL_STATE(7)] = 212,
  [SMALL_STATE(8)] = 256,
  [SMALL_STATE(9)] = 300,
  [SMALL_STATE(10)] = 330,
  [SMALL_STATE(11)] = 368,
  [SMALL_STATE(12)] = 406,
  [SMALL_STATE(13)] = 450,
  [SMALL_STATE(14)] = 478,
  [SMALL_STATE(15)] = 522,
  [SMALL_STATE(16)] = 566,
  [SMALL_STATE(17)] = 610,
  [SMALL_STATE(18)] = 654,
  [SMALL_STATE(19)] = 698,
  [SMALL_STATE(20)] = 739,
  [SMALL_STATE(21)] = 780,
  [SMALL_STATE(22)] = 821,
  [SMALL_STATE(23)] = 862,
  [SMALL_STATE(24)] = 903,
  [SMALL_STATE(25)] = 944,
  [SMALL_STATE(26)] = 985,
  [SMALL_STATE(27)] = 1026,
  [SMALL_STATE(28)] = 1067,
  [SMALL_STATE(29)] = 1108,
  [SMALL_STATE(30)] = 1149,
  [SMALL_STATE(31)] = 1186,
  [SMALL_STATE(32)] = 1223,
  [SMALL_STATE(33)] = 1252,
  [SMALL_STATE(34)] = 1281,
  [SMALL_STATE(35)] = 1310,
  [SMALL_STATE(36)] = 1339,
  [SMALL_STATE(37)] = 1368,
  [SMALL_STATE(38)] = 1397,
  [SMALL_STATE(39)] = 1426,
  [SMALL_STATE(40)] = 1455,
  [SMALL_STATE(41)] = 1476,
  [SMALL_STATE(42)] = 1505,
  [SMALL_STATE(43)] = 1534,
  [SMALL_STATE(44)] = 1563,
  [SMALL_STATE(45)] = 1592,
  [SMALL_STATE(46)] = 1621,
  [SMALL_STATE(47)] = 1642,
  [SMALL_STATE(48)] = 1671,
  [SMALL_STATE(49)] = 1700,
  [SMALL_STATE(50)] = 1729,
  [SMALL_STATE(51)] = 1758,
  [SMALL_STATE(52)] = 1787,
  [SMALL_STATE(53)] = 1816,
  [SMALL_STATE(54)] = 1845,
  [SMALL_STATE(55)] = 1874,
  [SMALL_STATE(56)] = 1903,
  [SMALL_STATE(57)] = 1932,
  [SMALL_STATE(58)] = 1961,
  [SMALL_STATE(59)] = 1990,
  [SMALL_STATE(60)] = 2019,
  [SMALL_STATE(61)] = 2038,
  [SMALL_STATE(62)] = 2057,
  [SMALL_STATE(63)] = 2081,
  [SMALL_STATE(64)] = 2094,
  [SMALL_STATE(65)] = 2113,
  [SMALL_STATE(66)] = 2132,
  [SMALL_STATE(67)] = 2155,
  [SMALL_STATE(68)] = 2178,
  [SMALL_STATE(69)] = 2191,
  [SMALL_STATE(70)] = 2206,
  [SMALL_STATE(71)] = 2229,
  [SMALL_STATE(72)] = 2252,
  [SMALL_STATE(73)] = 2265,
  [SMALL_STATE(74)] = 2284,
  [SMALL_STATE(75)] = 2303,
  [SMALL_STATE(76)] = 2317,
  [SMALL_STATE(77)] = 2331,
  [SMALL_STATE(78)] = 2343,
  [SMALL_STATE(79)] = 2357,
  [SMALL_STATE(80)] = 2367,
  [SMALL_STATE(81)] = 2381,
  [SMALL_STATE(82)] = 2394,
  [SMALL_STATE(83)] = 2407,
  [SMALL_STATE(84)] = 2420,
  [SMALL_STATE(85)] = 2433,
  [SMALL_STATE(86)] = 2446,
  [SMALL_STATE(87)] = 2459,
  [SMALL_STATE(88)] = 2472,
  [SMALL_STATE(89)] = 2485,
  [SMALL_STATE(90)] = 2498,
  [SMALL_STATE(91)] = 2511,
  [SMALL_STATE(92)] = 2524,
  [SMALL_STATE(93)] = 2537,
  [SMALL_STATE(94)] = 2550,
  [SMALL_STATE(95)] = 2563,
  [SMALL_STATE(96)] = 2576,
  [SMALL_STATE(97)] = 2589,
  [SMALL_STATE(98)] = 2602,
  [SMALL_STATE(99)] = 2615,
  [SMALL_STATE(100)] = 2628,
  [SMALL_STATE(101)] = 2636,
  [SMALL_STATE(102)] = 2644,
  [SMALL_STATE(103)] = 2654,
  [SMALL_STATE(104)] = 2662,
  [SMALL_STATE(105)] = 2672,
  [SMALL_STATE(106)] = 2682,
  [SMALL_STATE(107)] = 2692,
  [SMALL_STATE(108)] = 2702,
  [SMALL_STATE(109)] = 2710,
  [SMALL_STATE(110)] = 2720,
  [SMALL_STATE(111)] = 2730,
  [SMALL_STATE(112)] = 2740,
  [SMALL_STATE(113)] = 2748,
  [SMALL_STATE(114)] = 2755,
  [SMALL_STATE(115)] = 2762,
  [SMALL_STATE(116)] = 2769,
  [SMALL_STATE(117)] = 2776,
  [SMALL_STATE(118)] = 2783,
  [SMALL_STATE(119)] = 2790,
  [SMALL_STATE(120)] = 2797,
  [SMALL_STATE(121)] = 2804,
  [SMALL_STATE(122)] = 2811,
  [SMALL_STATE(123)] = 2818,
  [SMALL_STATE(124)] = 2825,
  [SMALL_STATE(125)] = 2832,
  [SMALL_STATE(126)] = 2839,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(124),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(105),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tm_lam, 6),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tm_fun, 3, .production_id = 3),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tm_fun, 3, .production_id = 3),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tm_fun, 3, .production_id = 2),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tm_ascrip, 3),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tm_ascrip, 3),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tm_pi, 6),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tm_pi, 4),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tm_lam, 4),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tm_app, 2),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tm_app, 2),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tm_fun, 3, .production_id = 2),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tm_lam, 6),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tm_pi, 6),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decl, 3),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tm_lam, 4),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tm_pi, 4),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_solve_decl, 4),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_defn, 3),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_defn, 5),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [111] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(124),
  [114] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(103),
  [117] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(91),
  [120] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(74),
  [123] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(121),
  [126] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(105),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [131] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [133] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [137] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [139] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [141] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [143] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tm_bracket, 3),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tm_bracket, 3),
  [149] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [151] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [153] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [155] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [157] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__term, 1, .production_id = 1),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__term, 1, .production_id = 1),
  [163] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [165] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [167] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [169] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [171] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [173] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [175] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [177] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [179] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [181] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [183] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [185] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [187] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [189] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_order_repeat1, 2), SHIFT_REPEAT(66),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_order_repeat1, 2),
  [194] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_order_repeat1, 2), SHIFT_REPEAT(67),
  [197] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_order_repeat1, 2), SHIFT_REPEAT(92),
  [200] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_order_repeat1, 2), SHIFT_REPEAT(68),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_order, 3),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mode_decl, 2),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_mode_decl_repeat1, 2),
  [211] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_mode_decl_repeat1, 2), SHIFT_REPEAT(122),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_order, 1),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__declaration, 2),
  [228] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__declaration, 2),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_order, 2),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mode_decl, 3),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_mode_decl_repeat3, 2),
  [238] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_mode_decl_repeat3, 2), SHIFT_REPEAT(75),
  [241] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_callpat, 2),
  [245] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_callpat_repeat1, 2), SHIFT_REPEAT(78),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_callpat_repeat1, 2),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mid, 2),
  [252] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_callpat, 1),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_worlds_decl, 3),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_worlds_decl, 4),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_worlds_decl, 5),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_worlds_decl_repeat1, 2),
  [278] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_worlds_decl_repeat1, 2), SHIFT_REPEAT(114),
  [281] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_total_decl_repeat1, 2),
  [283] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_total_decl_repeat1, 2), SHIFT_REPEAT(102),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [290] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mode_decl, 4),
  [292] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_worlds_decl, 6),
  [294] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_total_decl, 2),
  [296] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_mode_decl_repeat2, 2), SHIFT_REPEAT(77),
  [299] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_mode_decl_repeat2, 2),
  [301] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_total_decl, 3),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [305] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_mode_decl_repeat2, 6),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [309] = {.entry = {.count = 1, .reusable = false}}, SHIFT(116),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [327] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_mode_decl_repeat2, 4),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [341] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_total_decl_repeat1, 3),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [357] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [361] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mode, 1),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [367] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [369] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_twelf(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
